<?php

use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('municipios')->insert([
            ['id'=>"1",'municipio'=> "EL ENCANTO",'departamento_id'=> "1"],
            ['id'=>"2",'municipio'=> "LA CHORRERA",'departamento_id'=> "1"],
            ['id'=>"3",'municipio'=> "LA PEDRERA",'departamento_id'=> "1"],
            ['id'=>"4",'municipio'=> "LA VICTORIA",'departamento_id'=> "1"],
            ['id'=>"5",'municipio'=> "LETICIA",'departamento_id'=> "1"],
            ['id'=>"6",'municipio'=> "MIRITI",'departamento_id'=> "1"],
            ['id'=>"7",'municipio'=> "PUERTO ALEGRIA",'departamento_id'=> "1"],
            ['id'=>"8",'municipio'=> "PUERTO ARICA",'departamento_id'=> "1"],
            ['id'=>"9",'municipio'=> "PUERTO NARIÑO",'departamento_id'=> "1"],
            ['id'=>"10",'municipio'=> "PUERTO SANTANDER",'departamento_id'=> "1"],
            ['id'=>"11",'municipio'=> "TURAPACA",'departamento_id'=> "1"],
            ['id'=>"12",'municipio'=> "ABEJORRAL",'departamento_id'=> "2"],
            ['id'=>"13",'municipio'=> "ABRIAQUI",'departamento_id'=> "2"],
            ['id'=>"14",'municipio'=> "ALEJANDRIA",'departamento_id'=> "2"],
            ['id'=>"15",'municipio'=> "AMAGA",'departamento_id'=> "2"],
            ['id'=>"16",'municipio'=> "AMALFI",'departamento_id'=> "2"],
            ['id'=>"17",'municipio'=> "ANDES",'departamento_id'=> "2"],
            ['id'=>"18",'municipio'=> "ANGELOPOLIS",'departamento_id'=> "2"],
            ['id'=>"19",'municipio'=> "ANGOSTURA",'departamento_id'=> "2"],
            ['id'=>"20",'municipio'=> "ANORI",'departamento_id'=> "2"],
            ['id'=>"21",'municipio'=> "ANTIOQUIA",'departamento_id'=> "2"],
            ['id'=>"22",'municipio'=> "ANZA",'departamento_id'=> "2"],
            ['id'=>"23",'municipio'=> "APARTADO",'departamento_id'=> "2"],
            ['id'=>"24",'municipio'=> "ARBOLETES",'departamento_id'=> "2"],
            ['id'=>"25",'municipio'=> "ARGELIA",'departamento_id'=> "2"],
            ['id'=>"26",'municipio'=> "ARMENIA",'departamento_id'=> "2"],
            ['id'=>"27",'municipio'=> "BARBOSA",'departamento_id'=> "2"],
            ['id'=>"28",'municipio'=> "BELLO",'departamento_id'=> "2"],
            ['id'=>"29",'municipio'=> "BELMIRA",'departamento_id'=> "2"],
            ['id'=>"30",'municipio'=> "BETANIA",'departamento_id'=> "2"],
            ['id'=>"31",'municipio'=> "BETULIA",'departamento_id'=> "2"],
            ['id'=>"32",'municipio'=> "BOLIVAR",'departamento_id'=> "2"],
            ['id'=>"33",'municipio'=> "BRICEÑO",'departamento_id'=> "2"],
            ['id'=>"34",'municipio'=> "BURITICA",'departamento_id'=> "2"],
            ['id'=>"35",'municipio'=> "CACERES",'departamento_id'=> "2"],
            ['id'=>"36",'municipio'=> "CAICEDO",'departamento_id'=> "2"],
            ['id'=>"37",'municipio'=> "CALDAS",'departamento_id'=> "2"],
            ['id'=>"38",'municipio'=> "CAMPAMENTO",'departamento_id'=> "2"],
            ['id'=>"39",'municipio'=> "CANASGORDAS",'departamento_id'=> "2"],
            ['id'=>"40",'municipio'=> "CARACOLI",'departamento_id'=> "2"],
            ['id'=>"41",'municipio'=> "CARAMANTA",'departamento_id'=> "2"],
            ['id'=>"42",'municipio'=> "CAREPA",'departamento_id'=> "2"],
            ['id'=>"43",'municipio'=> "CARMEN DE VIBORAL",'departamento_id'=> "2"],
            ['id'=>"44",'municipio'=> "CAROLINA DEL PRINCIPE",'departamento_id'=> "2"],
            ['id'=>"45",'municipio'=> "CAUCASIA",'departamento_id'=> "2"],
            ['id'=>"46",'municipio'=> "CHIGORODO",'departamento_id'=> "2"],
            ['id'=>"47",'municipio'=> "CISNEROS",'departamento_id'=> "2"],
            ['id'=>"48",'municipio'=> "COCORNA",'departamento_id'=> "2"],
            ['id'=>"49",'municipio'=> "CONCEPCION",'departamento_id'=> "2"],
            ['id'=>"50",'municipio'=> "CONCORDIA",'departamento_id'=> "2"],
            ['id'=>"51",'municipio'=> "COPACABANA",'departamento_id'=> "2"],
            ['id'=>"52",'municipio'=> "DABEIBA",'departamento_id'=> "2"],
            ['id'=>"53",'municipio'=> "DONMATIAS",'departamento_id'=> "2"],
            ['id'=>"54",'municipio'=> "EBEJICO",'departamento_id'=> "2"],
            ['id'=>"55",'municipio'=> "EL BAGRE",'departamento_id'=> "2"],
            ['id'=>"56",'municipio'=> "EL PENOL",'departamento_id'=> "2"],
            ['id'=>"57",'municipio'=> "EL RETIRO",'departamento_id'=> "2"],
            ['id'=>"58",'municipio'=> "ENTRERRIOS",'departamento_id'=> "2"],
            ['id'=>"59",'municipio'=> "ENVIGADO",'departamento_id'=> "2"],
            ['id'=>"60",'municipio'=> "FREDONIA",'departamento_id'=> "2"],
            ['id'=>"61",'municipio'=> "FRONTINO",'departamento_id'=> "2"],
            ['id'=>"62",'municipio'=> "GIRALDO",'departamento_id'=> "2"],
            ['id'=>"63",'municipio'=> "GIRARDOTA",'departamento_id'=> "2"],
            ['id'=>"64",'municipio'=> "GOMEZ PLATA",'departamento_id'=> "2"],
            ['id'=>"65",'municipio'=> "GRANADA",'departamento_id'=> "2"],
            ['id'=>"66",'municipio'=> "GUADALUPE",'departamento_id'=> "2"],
            ['id'=>"67",'municipio'=> "GUARNE",'departamento_id'=> "2"],
            ['id'=>"68",'municipio'=> "GUATAQUE",'departamento_id'=> "2"],
            ['id'=>"69",'municipio'=> "HELICONIA",'departamento_id'=> "2"],
            ['id'=>"70",'municipio'=> "HISPANIA",'departamento_id'=> "2"],
            ['id'=>"71",'municipio'=> "ITAGUI",'departamento_id'=> "2"],
            ['id'=>"72",'municipio'=> "ITUANGO",'departamento_id'=> "2"],
            ['id'=>"73",'municipio'=> "JARDIN",'departamento_id'=> "2"],
            ['id'=>"74",'municipio'=> "JERICO",'departamento_id'=> "2"],
            ['id'=>"75",'municipio'=> "LA CEJA",'departamento_id'=> "2"],
            ['id'=>"76",'municipio'=> "LA ESTRELLA",'departamento_id'=> "2"],
            ['id'=>"77",'municipio'=> "LA PINTADA",'departamento_id'=> "2"],
            ['id'=>"78",'municipio'=> "LA UNION",'departamento_id'=> "2"],
            ['id'=>"79",'municipio'=> "LIBORINA",'departamento_id'=> "2"],
            ['id'=>"80",'municipio'=> "MACEO",'departamento_id'=> "2"],
            ['id'=>"81",'municipio'=> "MARINILLA",'departamento_id'=> "2"],
            ['id'=>"82",'municipio'=> "MEDELLIN",'departamento_id'=> "2"],
            ['id'=>"83",'municipio'=> "MONTEBELLO",'departamento_id'=> "2"],
            ['id'=>"84",'municipio'=> "MURINDO",'departamento_id'=> "2"],
            ['id'=>"85",'municipio'=> "MUTATA",'departamento_id'=> "2"],
            ['id'=>"86",'municipio'=> "NARINO",'departamento_id'=> "2"],
            ['id'=>"87",'municipio'=> "NECHI",'departamento_id'=> "2"],
            ['id'=>"88",'municipio'=> "NECOCLI",'departamento_id'=> "2"],
            ['id'=>"89",'municipio'=> "OLAYA",'departamento_id'=> "2"],
            ['id'=>"90",'municipio'=> "PEQUE",'departamento_id'=> "2"],
            ['id'=>"91",'municipio'=> "PUEBLORRICO",'departamento_id'=> "2"],
            ['id'=>"92",'municipio'=> "PUERTO BERRIO",'departamento_id'=> "2"],
            ['id'=>"93",'municipio'=> "PUERTO NARE",'departamento_id'=> "2"],
            ['id'=>"94",'municipio'=> "PUERTO TRIUNFO",'departamento_id'=> "2"],
            ['id'=>"95",'municipio'=> "REMEDIOS",'departamento_id'=> "2"],
            ['id'=>"96",'municipio'=> "RIONEGRO",'departamento_id'=> "2"],
            ['id'=>"97",'municipio'=> "SABANALARGA",'departamento_id'=> "2"],
            ['id'=>"98",'municipio'=> "SABANETA",'departamento_id'=> "2"],
            ['id'=>"99",'municipio'=> "SALGAR",'departamento_id'=> "2"],
            ['id'=>"100",'municipio'=> "SAN ANDRES DE CUERQUIA",'departamento_id'=> "2"],
            ['id'=>"101",'municipio'=> "SAN CARLOS",'departamento_id'=> "2"],
            ['id'=>"102",'municipio'=> "SAN FRANCISCO",'departamento_id'=> "2"],
            ['id'=>"103",'municipio'=> "SAN JERONIMO",'departamento_id'=> "2"],
            ['id'=>"104",'municipio'=> "SAN JOSE DE LA MONTAÑA",'departamento_id'=> "2"],
            ['id'=>"105",'municipio'=> "SAN JUAN DE URABA",'departamento_id'=> "2"],
            ['id'=>"106",'municipio'=> "SAN LUIS",'departamento_id'=> "2"],
            ['id'=>"107",'municipio'=> "SAN PEDRO DE LOS MILAGROS",'departamento_id'=> "2"],
            ['id'=>"108",'municipio'=> "SAN PEDRO DE URABA",'departamento_id'=> "2"],
            ['id'=>"109",'municipio'=> "SAN RAFAEL",'departamento_id'=> "2"],
            ['id'=>"110",'municipio'=> "SAN ROQUE",'departamento_id'=> "2"],
            ['id'=>"111",'municipio'=> "SAN VICENTE",'departamento_id'=> "2"],
            ['id'=>"112",'municipio'=> "SANTA BARBARA",'departamento_id'=> "2"],
            ['id'=>"113",'municipio'=> "SANTA ROSA DE OSOS",'departamento_id'=> "2"],
            ['id'=>"114",'municipio'=> "SANTO DOMINGO",'departamento_id'=> "2"],
            ['id'=>"115",'municipio'=> "SANTUARIO",'departamento_id'=> "2"],
            ['id'=>"116",'municipio'=> "SEGOVIA",'departamento_id'=> "2"],
            ['id'=>"117",'municipio'=> "SONSON",'departamento_id'=> "2"],
            ['id'=>"118",'municipio'=> "SOPETRAN",'departamento_id'=> "2"],
            ['id'=>"119",'municipio'=> "TAMESIS",'departamento_id'=> "2"],
            ['id'=>"120",'municipio'=> "TARAZA",'departamento_id'=> "2"],
            ['id'=>"121",'municipio'=> "TARSO",'departamento_id'=> "2"],
            ['id'=>"122",'municipio'=> "TITIRIBI",'departamento_id'=> "2"],
            ['id'=>"123",'municipio'=> "TOLEDO",'departamento_id'=> "2"],
            ['id'=>"124",'municipio'=> "TURBO",'departamento_id'=> "2"],
            ['id'=>"125",'municipio'=> "URAMITA",'departamento_id'=> "2"],
            ['id'=>"126",'municipio'=> "URRAO",'departamento_id'=> "2"],
            ['id'=>"127",'municipio'=> "VALDIVIA",'departamento_id'=> "2"],
            ['id'=>"128",'municipio'=> "VALPARAISO",'departamento_id'=> "2"],
            ['id'=>"129",'municipio'=> "VEGACHI",'departamento_id'=> "2"],
            ['id'=>"130",'municipio'=> "VENECIA",'departamento_id'=> "2"],
            ['id'=>"131",'municipio'=> "VIGIA DEL FUERTE",'departamento_id'=> "2"],
            ['id'=>"132",'municipio'=> "YALI",'departamento_id'=> "2"],
            ['id'=>"133",'municipio'=> "YARUMAL",'departamento_id'=> "2"],
            ['id'=>"134",'municipio'=> "YOLOMBO",'departamento_id'=> "2"],
            ['id'=>"135",'municipio'=> "YONDO",'departamento_id'=> "2"],
            ['id'=>"136",'municipio'=> "ZARAGOZA",'departamento_id'=> "2"],
            ['id'=>"137",'municipio'=> "ARAUCA",'departamento_id'=> "3"],
            ['id'=>"138",'municipio'=> "ARAUQUITA",'departamento_id'=> "3"],
            ['id'=>"139",'municipio'=> "CRAVO NORTE",'departamento_id'=> "3"],
            ['id'=>"140",'municipio'=> "FORTUL",'departamento_id'=> "3"],
            ['id'=>"141",'municipio'=> "PUERTO RONDON",'departamento_id'=> "3"],
            ['id'=>"142",'municipio'=> "SARAVENA",'departamento_id'=> "3"],
            ['id'=>"143",'municipio'=> "TAME",'departamento_id'=> "3"],
            ['id'=>"144",'municipio'=> "BARANOA",'departamento_id'=> "4"],
            ['id'=>"145",'municipio'=> "BARRANQUILLA",'departamento_id'=> "4"],
            ['id'=>"146",'municipio'=> "CAMPO DE LA CRUZ",'departamento_id'=> "4"],
            ['id'=>"147",'municipio'=> "CANDELARIA",'departamento_id'=> "4"],
            ['id'=>"148",'municipio'=> "GALAPA",'departamento_id'=> "4"],
            ['id'=>"149",'municipio'=> "JUAN DE ACOSTA",'departamento_id'=> "4"],
            ['id'=>"150",'municipio'=> "LURUACO",'departamento_id'=> "4"],
            ['id'=>"151",'municipio'=> "MALAMBO",'departamento_id'=> "4"],
            ['id'=>"152",'municipio'=> "MANATI",'departamento_id'=> "4"],
            ['id'=>"153",'municipio'=> "PALMAR DE VARELA",'departamento_id'=> "4"],
            ['id'=>"154",'municipio'=> "PIOJO",'departamento_id'=> "4"],
            ['id'=>"155",'municipio'=> "POLO NUEVO",'departamento_id'=> "4"],
            ['id'=>"156",'municipio'=> "PONEDERA",'departamento_id'=> "4"],
            ['id'=>"157",'municipio'=> "PUERTO COLOMBIA",'departamento_id'=> "4"],
            ['id'=>"158",'municipio'=> "REPELON",'departamento_id'=> "4"],
            ['id'=>"159",'municipio'=> "SABANAGRANDE",'departamento_id'=> "4"],
            ['id'=>"160",'municipio'=> "SABANALARGA",'departamento_id'=> "4"],
            ['id'=>"161",'municipio'=> "SANTA LUCIA",'departamento_id'=> "4"],
            ['id'=>"162",'municipio'=> "SANTO TOMAS",'departamento_id'=> "4"],
            ['id'=>"163",'municipio'=> "SOLEDAD",'departamento_id'=> "4"],
            ['id'=>"164",'municipio'=> "SUAN",'departamento_id'=> "4"],
            ['id'=>"165",'municipio'=> "TUBARA",'departamento_id'=> "4"],
            ['id'=>"166",'municipio'=> "USIACURI",'departamento_id'=> "4"],
            ['id'=>"167",'municipio'=> "ACHI",'departamento_id'=> "5"],
            ['id'=>"168",'municipio'=> "ALTOS DEL ROSARIO",'departamento_id'=> "5"],
            ['id'=>"169",'municipio'=> "ARENAL",'departamento_id'=> "5"],
            ['id'=>"170",'municipio'=> "ARJONA",'departamento_id'=> "5"],
            ['id'=>"171",'municipio'=> "ARROYOHONDO",'departamento_id'=> "5"],
            ['id'=>"172",'municipio'=> "BARRANCO DE LOBA",'departamento_id'=> "5"],
            ['id'=>"173",'municipio'=> "BRAZUELO DE PAPAYAL",'departamento_id'=> "5"],
            ['id'=>"174",'municipio'=> "CALAMAR",'departamento_id'=> "5"],
            ['id'=>"175",'municipio'=> "CANTAGALLO",'departamento_id'=> "5"],
            ['id'=>"176",'municipio'=> "CARTAGENA DE INDIAS",'departamento_id'=> "5"],
            ['id'=>"177",'municipio'=> "CICUCO",'departamento_id'=> "5"],
            ['id'=>"178",'municipio'=> "CLEMENCIA",'departamento_id'=> "5"],
            ['id'=>"179",'municipio'=> "CORDOBA",'departamento_id'=> "5"],
            ['id'=>"180",'municipio'=> "EL CARMEN DE BOLIVAR",'departamento_id'=> "5"],
            ['id'=>"181",'municipio'=> "EL GUAMO",'departamento_id'=> "5"],
            ['id'=>"182",'municipio'=> "EL PENION",'departamento_id'=> "5"],
            ['id'=>"183",'municipio'=> "HATILLO DE LOBA",'departamento_id'=> "5"],
            ['id'=>"184",'municipio'=> "MAGANGUE",'departamento_id'=> "5"],
            ['id'=>"185",'municipio'=> "MAHATES",'departamento_id'=> "5"],
            ['id'=>"186",'municipio'=> "MARGARITA",'departamento_id'=> "5"],
            ['id'=>"187",'municipio'=> "MARIA LA BAJA",'departamento_id'=> "5"],
            ['id'=>"188",'municipio'=> "MONTECRISTO",'departamento_id'=> "5"],
            ['id'=>"189",'municipio'=> "MORALES",'departamento_id'=> "5"],
            ['id'=>"190",'municipio'=> "MORALES",'departamento_id'=> "5"],
            ['id'=>"191",'municipio'=> "NOROSI",'departamento_id'=> "5"],
            ['id'=>"192",'municipio'=> "PINILLOS",'departamento_id'=> "5"],
            ['id'=>"193",'municipio'=> "REGIDOR",'departamento_id'=> "5"],
            ['id'=>"194",'municipio'=> "RIO VIEJO",'departamento_id'=> "5"],
            ['id'=>"195",'municipio'=> "SAN CRISTOBAL",'departamento_id'=> "5"],
            ['id'=>"196",'municipio'=> "SAN ESTANISLAO",'departamento_id'=> "5"],
            ['id'=>"197",'municipio'=> "SAN FERNANDO",'departamento_id'=> "5"],
            ['id'=>"198",'municipio'=> "SAN JACINTO",'departamento_id'=> "5"],
            ['id'=>"199",'municipio'=> "SAN JACINTO DEL CAUCA",'departamento_id'=> "5"],
            ['id'=>"200",'municipio'=> "SAN JUAN DE NEPOMUCENO",'departamento_id'=> "5"],
            ['id'=>"201",'municipio'=> "SAN MARTIN DE LOBA",'departamento_id'=> "5"],
            ['id'=>"202",'municipio'=> "SAN PABLO",'departamento_id'=> "5"],
            ['id'=>"203",'municipio'=> "SAN PABLO NORTE",'departamento_id'=> "5"],
            ['id'=>"204",'municipio'=> "SANTA CATALINA",'departamento_id'=> "5"],
            ['id'=>"205",'municipio'=> "SANTA CRUZ DE MOMPOX",'departamento_id'=> "5"],
            ['id'=>"206",'municipio'=> "SANTA ROSA",'departamento_id'=> "5"],
            ['id'=>"207",'municipio'=> "SANTA ROSA DEL SUR",'departamento_id'=> "5"],
            ['id'=>"208",'municipio'=> "SIMITI",'departamento_id'=> "5"],
            ['id'=>"209",'municipio'=> "SOPLAVIENTO",'departamento_id'=> "5"],
            ['id'=>"210",'municipio'=> "TALAIGUA NUEVO",'departamento_id'=> "5"],
            ['id'=>"211",'municipio'=> "TUQUISIO",'departamento_id'=> "5"],
            ['id'=>"212",'municipio'=> "TURBACO",'departamento_id'=> "5"],
            ['id'=>"213",'municipio'=> "TURBANA",'departamento_id'=> "5"],
            ['id'=>"214",'municipio'=> "VILLANUEVA",'departamento_id'=> "5"],
            ['id'=>"215",'municipio'=> "ZAMBRANO",'departamento_id'=> "5"],
            ['id'=>"216",'municipio'=> "AQUITANIA",'departamento_id'=> "6"],
            ['id'=>"217",'municipio'=> "ARCABUCO",'departamento_id'=> "6"],
            ['id'=>"218",'municipio'=> "BELÉN",'departamento_id'=> "6"],
            ['id'=>"219",'municipio'=> "BERBEO",'departamento_id'=> "6"],
            ['id'=>"220",'municipio'=> "BETÉITIVA",'departamento_id'=> "6"],
            ['id'=>"221",'municipio'=> "BOAVITA",'departamento_id'=> "6"],
            ['id'=>"222",'municipio'=> "BOYACÁ",'departamento_id'=> "6"],
            ['id'=>"223",'municipio'=> "BRICEÑO",'departamento_id'=> "6"],
            ['id'=>"224",'municipio'=> "BUENAVISTA",'departamento_id'=> "6"],
            ['id'=>"225",'municipio'=> "BUSBANZÁ",'departamento_id'=> "6"],
            ['id'=>"226",'municipio'=> "CALDAS",'departamento_id'=> "6"],
            ['id'=>"227",'municipio'=> "CAMPO HERMOSO",'departamento_id'=> "6"],
            ['id'=>"228",'municipio'=> "CERINZA",'departamento_id'=> "6"],
            ['id'=>"229",'municipio'=> "CHINAVITA",'departamento_id'=> "6"],
            ['id'=>"230",'municipio'=> "CHIQUINQUIRÁ",'departamento_id'=> "6"],
            ['id'=>"231",'municipio'=> "CHÍQUIZA",'departamento_id'=> "6"],
            ['id'=>"232",'municipio'=> "CHISCAS",'departamento_id'=> "6"],
            ['id'=>"233",'municipio'=> "CHITA",'departamento_id'=> "6"],
            ['id'=>"234",'municipio'=> "CHITARAQUE",'departamento_id'=> "6"],
            ['id'=>"235",'municipio'=> "CHIVATÁ",'departamento_id'=> "6"],
            ['id'=>"236",'municipio'=> "CIÉNEGA",'departamento_id'=> "6"],
            ['id'=>"237",'municipio'=> "CÓMBITA",'departamento_id'=> "6"],
            ['id'=>"238",'municipio'=> "COPER",'departamento_id'=> "6"],
            ['id'=>"239",'municipio'=> "CORRALES",'departamento_id'=> "6"],
            ['id'=>"240",'municipio'=> "COVARACHÍA",'departamento_id'=> "6"],
            ['id'=>"241",'municipio'=> "CUBARA",'departamento_id'=> "6"],
            ['id'=>"242",'municipio'=> "CUCAITA",'departamento_id'=> "6"],
            ['id'=>"243",'municipio'=> "CUITIVA",'departamento_id'=> "6"],
            ['id'=>"244",'municipio'=> "DUITAMA",'departamento_id'=> "6"],
            ['id'=>"245",'municipio'=> "EL COCUY",'departamento_id'=> "6"],
            ['id'=>"246",'municipio'=> "EL ESPINO",'departamento_id'=> "6"],
            ['id'=>"247",'municipio'=> "FIRAVITOBA",'departamento_id'=> "6"],
            ['id'=>"248",'municipio'=> "FLORESTA",'departamento_id'=> "6"],
            ['id'=>"249",'municipio'=> "GACHANTIVÁ",'departamento_id'=> "6"],
            ['id'=>"250",'municipio'=> "GÁMEZA",'departamento_id'=> "6"],
            ['id'=>"251",'municipio'=> "GARAGOA",'departamento_id'=> "6"],
            ['id'=>"252",'municipio'=> "GUACAMAYAS",'departamento_id'=> "6"],
            ['id'=>"253",'municipio'=> "GÜICÁN",'departamento_id'=> "6"],
            ['id'=>"254",'municipio'=> "IZA",'departamento_id'=> "6"],
            ['id'=>"255",'municipio'=> "JENESANO",'departamento_id'=> "6"],
            ['id'=>"256",'municipio'=> "JERICÓ",'departamento_id'=> "6"],
            ['id'=>"257",'municipio'=> "LA UVITA",'departamento_id'=> "6"],
            ['id'=>"258",'municipio'=> "LA VICTORIA",'departamento_id'=> "6"],
            ['id'=>"259",'municipio'=> "LABRANZA GRANDE",'departamento_id'=> "6"],
            ['id'=>"260",'municipio'=> "MACANAL",'departamento_id'=> "6"],
            ['id'=>"261",'municipio'=> "MARIPÍ",'departamento_id'=> "6"],
            ['id'=>"262",'municipio'=> "MIRAFLORES",'departamento_id'=> "6"],
            ['id'=>"263",'municipio'=> "MONGUA",'departamento_id'=> "6"],
            ['id'=>"264",'municipio'=> "MONGUÍ",'departamento_id'=> "6"],
            ['id'=>"265",'municipio'=> "MONIQUIRÁ",'departamento_id'=> "6"],
            ['id'=>"266",'municipio'=> "MOTAVITA",'departamento_id'=> "6"],
            ['id'=>"267",'municipio'=> "MUZO",'departamento_id'=> "6"],
            ['id'=>"268",'municipio'=> "NOBSA",'departamento_id'=> "6"],
            ['id'=>"269",'municipio'=> "NUEVO COLÓN",'departamento_id'=> "6"],
            ['id'=>"270",'municipio'=> "OICATÁ",'departamento_id'=> "6"],
            ['id'=>"271",'municipio'=> "OTANCHE",'departamento_id'=> "6"],
            ['id'=>"272",'municipio'=> "PACHAVITA",'departamento_id'=> "6"],
            ['id'=>"273",'municipio'=> "PÁEZ",'departamento_id'=> "6"],
            ['id'=>"274",'municipio'=> "PAIPA",'departamento_id'=> "6"],
            ['id'=>"275",'municipio'=> "PAJARITO",'departamento_id'=> "6"],
            ['id'=>"276",'municipio'=> "PANQUEBA",'departamento_id'=> "6"],
            ['id'=>"277",'municipio'=> "PAUNA",'departamento_id'=> "6"],
            ['id'=>"278",'municipio'=> "PAYA",'departamento_id'=> "6"],
            ['id'=>"279",'municipio'=> "PAZ DE RÍO",'departamento_id'=> "6"],
            ['id'=>"280",'municipio'=> "PESCA",'departamento_id'=> "6"],
            ['id'=>"281",'municipio'=> "PISBA",'departamento_id'=> "6"],
            ['id'=>"282",'municipio'=> "PUERTO BOYACA",'departamento_id'=> "6"],
            ['id'=>"283",'municipio'=> "QUÍPAMA",'departamento_id'=> "6"],
            ['id'=>"284",'municipio'=> "RAMIRIQUÍ",'departamento_id'=> "6"],
            ['id'=>"285",'municipio'=> "RÁQUIRA",'departamento_id'=> "6"],
            ['id'=>"286",'municipio'=> "RONDÓN",'departamento_id'=> "6"],
            ['id'=>"287",'municipio'=> "SABOYÁ",'departamento_id'=> "6"],
            ['id'=>"288",'municipio'=> "SÁCHICA",'departamento_id'=> "6"],
            ['id'=>"289",'municipio'=> "SAMACÁ",'departamento_id'=> "6"],
            ['id'=>"290",'municipio'=> "SAN EDUARDO",'departamento_id'=> "6"],
            ['id'=>"291",'municipio'=> "SAN JOSÉ DE PARE",'departamento_id'=> "6"],
            ['id'=>"292",'municipio'=> "SAN LUÍS DE GACENO",'departamento_id'=> "6"],
            ['id'=>"293",'municipio'=> "SAN MATEO",'departamento_id'=> "6"],
            ['id'=>"294",'municipio'=> "SAN MIGUEL DE SEMA",'departamento_id'=> "6"],
            ['id'=>"295",'municipio'=> "SAN PABLO DE BORBUR",'departamento_id'=> "6"],
            ['id'=>"296",'municipio'=> "SANTA MARÍA",'departamento_id'=> "6"],
            ['id'=>"297",'municipio'=> "SANTA ROSA DE VITERBO",'departamento_id'=> "6"],
            ['id'=>"298",'municipio'=> "SANTA SOFÍA",'departamento_id'=> "6"],
            ['id'=>"299",'municipio'=> "SANTANA",'departamento_id'=> "6"],
            ['id'=>"300",'municipio'=> "SATIVANORTE",'departamento_id'=> "6"],
            ['id'=>"301",'municipio'=> "SATIVASUR",'departamento_id'=> "6"],
            ['id'=>"302",'municipio'=> "SIACHOQUE",'departamento_id'=> "6"],
            ['id'=>"303",'municipio'=> "SOATÁ",'departamento_id'=> "6"],
            ['id'=>"304",'municipio'=> "SOCHA",'departamento_id'=> "6"],
            ['id'=>"305",'municipio'=> "SOCOTÁ",'departamento_id'=> "6"],
            ['id'=>"306",'municipio'=> "SOGAMOSO",'departamento_id'=> "6"],
            ['id'=>"307",'municipio'=> "SORA",'departamento_id'=> "6"],
            ['id'=>"308",'municipio'=> "SORACÁ",'departamento_id'=> "6"],
            ['id'=>"309",'municipio'=> "SOTAQUIRÁ",'departamento_id'=> "6"],
            ['id'=>"310",'municipio'=> "SUSACÓN",'departamento_id'=> "6"],
            ['id'=>"311",'municipio'=> "SUTARMACHÁN",'departamento_id'=> "6"],
            ['id'=>"312",'municipio'=> "TASCO",'departamento_id'=> "6"],
            ['id'=>"313",'municipio'=> "TIBANÁ",'departamento_id'=> "6"],
            ['id'=>"314",'municipio'=> "TIBASOSA",'departamento_id'=> "6"],
            ['id'=>"315",'municipio'=> "TINJACÁ",'departamento_id'=> "6"],
            ['id'=>"316",'municipio'=> "TIPACOQUE",'departamento_id'=> "6"],
            ['id'=>"317",'municipio'=> "TOCA",'departamento_id'=> "6"],
            ['id'=>"318",'municipio'=> "TOGÜÍ",'departamento_id'=> "6"],
            ['id'=>"319",'municipio'=> "TÓPAGA",'departamento_id'=> "6"],
            ['id'=>"320",'municipio'=> "TOTA",'departamento_id'=> "6"],
            ['id'=>"321",'municipio'=> "TUNJA",'departamento_id'=> "6"],
            ['id'=>"322",'municipio'=> "TUNUNGUÁ",'departamento_id'=> "6"],
            ['id'=>"323",'municipio'=> "TURMEQUÉ",'departamento_id'=> "6"],
            ['id'=>"324",'municipio'=> "TUTA",'departamento_id'=> "6"],
            ['id'=>"325",'municipio'=> "TUTAZÁ",'departamento_id'=> "6"],
            ['id'=>"326",'municipio'=> "UMBITA",'departamento_id'=> "6"],
            ['id'=>"327",'municipio'=> "VENTA QUEMADA",'departamento_id'=> "6"],
            ['id'=>"328",'municipio'=> "VILLA DE LEYVA",'departamento_id'=> "6"],
            ['id'=>"329",'municipio'=> "VIRACACHÁ",'departamento_id'=> "6"],
            ['id'=>"330",'municipio'=> "ZETAQUIRA",'departamento_id'=> "6"],
            ['id'=>"331",'municipio'=> "AGUADAS",'departamento_id'=> "7"],
            ['id'=>"332",'municipio'=> "ANSERMA",'departamento_id'=> "7"],
            ['id'=>"333",'municipio'=> "ARANZAZU",'departamento_id'=> "7"],
            ['id'=>"334",'municipio'=> "BELALCAZAR",'departamento_id'=> "7"],
            ['id'=>"335",'municipio'=> "CHINCHINÁ",'departamento_id'=> "7"],
            ['id'=>"336",'municipio'=> "FILADELFIA",'departamento_id'=> "7"],
            ['id'=>"337",'municipio'=> "LA DORADA",'departamento_id'=> "7"],
            ['id'=>"338",'municipio'=> "LA MERCED",'departamento_id'=> "7"],
            ['id'=>"339",'municipio'=> "MANIZALES",'departamento_id'=> "7"],
            ['id'=>"340",'municipio'=> "MANZANARES",'departamento_id'=> "7"],
            ['id'=>"341",'municipio'=> "MARMATO",'departamento_id'=> "7"],
            ['id'=>"342",'municipio'=> "MARQUETALIA",'departamento_id'=> "7"],
            ['id'=>"343",'municipio'=> "MARULANDA",'departamento_id'=> "7"],
            ['id'=>"344",'municipio'=> "NEIRA",'departamento_id'=> "7"],
            ['id'=>"345",'municipio'=> "NORCASIA",'departamento_id'=> "7"],
            ['id'=>"346",'municipio'=> "PACORA",'departamento_id'=> "7"],
            ['id'=>"347",'municipio'=> "PALESTINA",'departamento_id'=> "7"],
            ['id'=>"348",'municipio'=> "PENSILVANIA",'departamento_id'=> "7"],
            ['id'=>"349",'municipio'=> "RIOSUCIO",'departamento_id'=> "7"],
            ['id'=>"350",'municipio'=> "RISARALDA",'departamento_id'=> "7"],
            ['id'=>"351",'municipio'=> "SALAMINA",'departamento_id'=> "7"],
            ['id'=>"352",'municipio'=> "SAMANA",'departamento_id'=> "7"],
            ['id'=>"353",'municipio'=> "SAN JOSE",'departamento_id'=> "7"],
            ['id'=>"354",'municipio'=> "SUPÍA",'departamento_id'=> "7"],
            ['id'=>"355",'municipio'=> "VICTORIA",'departamento_id'=> "7"],
            ['id'=>"356",'municipio'=> "VILLAMARÍA",'departamento_id'=> "7"],
            ['id'=>"357",'municipio'=> "VITERBO",'departamento_id'=> "7"],
            ['id'=>"358",'municipio'=> "ALBANIA",'departamento_id'=> "8"],
            ['id'=>"359",'municipio'=> "BELÉN ANDAQUIES",'departamento_id'=> "8"],
            ['id'=>"360",'municipio'=> "CARTAGENA DEL CHAIRA",'departamento_id'=> "8"],
            ['id'=>"361",'municipio'=> "CURILLO",'departamento_id'=> "8"],
            ['id'=>"362",'municipio'=> "EL DONCELLO",'departamento_id'=> "8"],
            ['id'=>"363",'municipio'=> "EL PAUJIL",'departamento_id'=> "8"],
            ['id'=>"364",'municipio'=> "FLORENCIA",'departamento_id'=> "8"],
            ['id'=>"365",'municipio'=> "LA MONTAÑITA",'departamento_id'=> "8"],
            ['id'=>"366",'municipio'=> "MILÁN",'departamento_id'=> "8"],
            ['id'=>"367",'municipio'=> "MORELIA",'departamento_id'=> "8"],
            ['id'=>"368",'municipio'=> "PUERTO RICO",'departamento_id'=> "8"],
            ['id'=>"369",'municipio'=> "SAN  VICENTE DEL CAGUAN",'departamento_id'=> "8"],
            ['id'=>"370",'municipio'=> "SAN JOSÉ DE FRAGUA",'departamento_id'=> "8"],
            ['id'=>"371",'municipio'=> "SOLANO",'departamento_id'=> "8"],
            ['id'=>"372",'municipio'=> "SOLITA",'departamento_id'=> "8"],
            ['id'=>"373",'municipio'=> "VALPARAÍSO",'departamento_id'=> "8"],
            ['id'=>"374",'municipio'=> "AGUAZUL",'departamento_id'=> "9"],
            ['id'=>"375",'municipio'=> "CHAMEZA",'departamento_id'=> "9"],
            ['id'=>"376",'municipio'=> "HATO COROZAL",'departamento_id'=> "9"],
            ['id'=>"377",'municipio'=> "LA SALINA",'departamento_id'=> "9"],
            ['id'=>"378",'municipio'=> "MANÍ",'departamento_id'=> "9"],
            ['id'=>"379",'municipio'=> "MONTERREY",'departamento_id'=> "9"],
            ['id'=>"380",'municipio'=> "NUNCHIA",'departamento_id'=> "9"],
            ['id'=>"381",'municipio'=> "OROCUE",'departamento_id'=> "9"],
            ['id'=>"382",'municipio'=> "PAZ DE ARIPORO",'departamento_id'=> "9"],
            ['id'=>"383",'municipio'=> "PORE",'departamento_id'=> "9"],
            ['id'=>"384",'municipio'=> "RECETOR",'departamento_id'=> "9"],
            ['id'=>"385",'municipio'=> "SABANA LARGA",'departamento_id'=> "9"],
            ['id'=>"386",'municipio'=> "SACAMA",'departamento_id'=> "9"],
            ['id'=>"387",'municipio'=> "SAN LUIS DE PALENQUE",'departamento_id'=> "9"],
            ['id'=>"388",'municipio'=> "TAMARA",'departamento_id'=> "9"],
            ['id'=>"389",'municipio'=> "TAURAMENA",'departamento_id'=> "9"],
            ['id'=>"390",'municipio'=> "TRINIDAD",'departamento_id'=> "9"],
            ['id'=>"391",'municipio'=> "VILLANUEVA",'departamento_id'=> "9"],
            ['id'=>"392",'municipio'=> "YOPAL",'departamento_id'=> "9"],
            ['id'=>"393",'municipio'=> "ALMAGUER",'departamento_id'=> "10"],
            ['id'=>"394",'municipio'=> "ARGELIA",'departamento_id'=> "10"],
            ['id'=>"395",'municipio'=> "BALBOA",'departamento_id'=> "10"],
            ['id'=>"396",'municipio'=> "BOLÍVAR",'departamento_id'=> "10"],
            ['id'=>"397",'municipio'=> "BUENOS AIRES",'departamento_id'=> "10"],
            ['id'=>"398",'municipio'=> "CAJIBIO",'departamento_id'=> "10"],
            ['id'=>"399",'municipio'=> "CALDONO",'departamento_id'=> "10"],
            ['id'=>"400",'municipio'=> "CALOTO",'departamento_id'=> "10"],
            ['id'=>"401",'municipio'=> "CORINTO",'departamento_id'=> "10"],
            ['id'=>"402",'municipio'=> "EL TAMBO",'departamento_id'=> "10"],
            ['id'=>"403",'municipio'=> "FLORENCIA",'departamento_id'=> "10"],
            ['id'=>"404",'municipio'=> "GUAPI",'departamento_id'=> "10"],
            ['id'=>"405",'municipio'=> "INZA",'departamento_id'=> "10"],
            ['id'=>"406",'municipio'=> "JAMBALÓ",'departamento_id'=> "10"],
            ['id'=>"407",'municipio'=> "LA SIERRA",'departamento_id'=> "10"],
            ['id'=>"408",'municipio'=> "LA VEGA",'departamento_id'=> "10"],
            ['id'=>"409",'municipio'=> "LÓPEZ",'departamento_id'=> "10"],
            ['id'=>"410",'municipio'=> "MERCADERES",'departamento_id'=> "10"],
            ['id'=>"411",'municipio'=> "MIRANDA",'departamento_id'=> "10"],
            ['id'=>"412",'municipio'=> "MORALES",'departamento_id'=> "10"],
            ['id'=>"413",'municipio'=> "PADILLA",'departamento_id'=> "10"],
            ['id'=>"414",'municipio'=> "PÁEZ",'departamento_id'=> "10"],
            ['id'=>"415",'municipio'=> "PATIA (EL BORDO)",'departamento_id'=> "10"],
            ['id'=>"416",'municipio'=> "PIAMONTE",'departamento_id'=> "10"],
            ['id'=>"417",'municipio'=> "PIENDAMO",'departamento_id'=> "10"],
            ['id'=>"418",'municipio'=> "POPAYÁN",'departamento_id'=> "10"],
            ['id'=>"419",'municipio'=> "PUERTO TEJADA",'departamento_id'=> "10"],
            ['id'=>"420",'municipio'=> "PURACE",'departamento_id'=> "10"],
            ['id'=>"421",'municipio'=> "ROSAS",'departamento_id'=> "10"],
            ['id'=>"422",'municipio'=> "SAN SEBASTIÁN",'departamento_id'=> "10"],
            ['id'=>"423",'municipio'=> "SANTA ROSA",'departamento_id'=> "10"],
            ['id'=>"424",'municipio'=> "SANTANDER DE QUILICHAO",'departamento_id'=> "10"],
            ['id'=>"425",'municipio'=> "SILVIA",'departamento_id'=> "10"],
            ['id'=>"426",'municipio'=> "SOTARA",'departamento_id'=> "10"],
            ['id'=>"427",'municipio'=> "SUÁREZ",'departamento_id'=> "10"],
            ['id'=>"428",'municipio'=> "SUCRE",'departamento_id'=> "10"],
            ['id'=>"429",'municipio'=> "TIMBÍO",'departamento_id'=> "10"],
            ['id'=>"430",'municipio'=> "TIMBIQUÍ",'departamento_id'=> "10"],
            ['id'=>"431",'municipio'=> "TORIBIO",'departamento_id'=> "10"],
            ['id'=>"432",'municipio'=> "TOTORO",'departamento_id'=> "10"],
            ['id'=>"433",'municipio'=> "VILLA RICA",'departamento_id'=> "10"],
            ['id'=>"434",'municipio'=> "AGUACHICA",'departamento_id'=> "11"],
            ['id'=>"435",'municipio'=> "AGUSTÍN CODAZZI",'departamento_id'=> "11"],
            ['id'=>"436",'municipio'=> "ASTREA",'departamento_id'=> "11"],
            ['id'=>"437",'municipio'=> "BECERRIL",'departamento_id'=> "11"],
            ['id'=>"438",'municipio'=> "BOSCONIA",'departamento_id'=> "11"],
            ['id'=>"439",'municipio'=> "CHIMICHAGUA",'departamento_id'=> "11"],
            ['id'=>"440",'municipio'=> "CHIRIGUANÁ",'departamento_id'=> "11"],
            ['id'=>"441",'municipio'=> "CURUMANÍ",'departamento_id'=> "11"],
            ['id'=>"442",'municipio'=> "EL COPEY",'departamento_id'=> "11"],
            ['id'=>"443",'municipio'=> "EL PASO",'departamento_id'=> "11"],
            ['id'=>"444",'municipio'=> "GAMARRA",'departamento_id'=> "11"],
            ['id'=>"445",'municipio'=> "GONZÁLEZ",'departamento_id'=> "11"],
            ['id'=>"446",'municipio'=> "LA GLORIA",'departamento_id'=> "11"],
            ['id'=>"447",'municipio'=> "LA JAGUA IBIRICO",'departamento_id'=> "11"],
            ['id'=>"448",'municipio'=> "MANAURE BALCÓN DEL CESAR",'departamento_id'=> "11"],
            ['id'=>"449",'municipio'=> "PAILITAS",'departamento_id'=> "11"],
            ['id'=>"450",'municipio'=> "PELAYA",'departamento_id'=> "11"],
            ['id'=>"451",'municipio'=> "PUEBLO BELLO",'departamento_id'=> "11"],
            ['id'=>"452",'municipio'=> "RÍO DE ORO",'departamento_id'=> "11"],
            ['id'=>"453",'municipio'=> "ROBLES (LA PAZ)",'departamento_id'=> "11"],
            ['id'=>"454",'municipio'=> "SAN ALBERTO",'departamento_id'=> "11"],
            ['id'=>"455",'municipio'=> "SAN DIEGO",'departamento_id'=> "11"],
            ['id'=>"456",'municipio'=> "SAN MARTÍN",'departamento_id'=> "11"],
            ['id'=>"457",'municipio'=> "TAMALAMEQUE",'departamento_id'=> "11"],
            ['id'=>"458",'municipio'=> "VALLEDUPAR",'departamento_id'=> "11"],
            ['id'=>"459",'municipio'=> "ACANDI",'departamento_id'=> "12"],
            ['id'=>"460",'municipio'=> "ALTO BAUDO (PIE DE PATO)",'departamento_id'=> "12"],
            ['id'=>"461",'municipio'=> "ATRATO",'departamento_id'=> "12"],
            ['id'=>"462",'municipio'=> "BAGADO",'departamento_id'=> "12"],
            ['id'=>"463",'municipio'=> "BAHIA SOLANO (MUTIS)",'departamento_id'=> "12"],
            ['id'=>"464",'municipio'=> "BAJO BAUDO (PIZARRO)",'departamento_id'=> "12"],
            ['id'=>"465",'municipio'=> "BOJAYA (BELLAVISTA)",'departamento_id'=> "12"],
            ['id'=>"466",'municipio'=> "CANTON DE SAN PABLO",'departamento_id'=> "12"],
            ['id'=>"467",'municipio'=> "CARMEN DEL DARIEN",'departamento_id'=> "12"],
            ['id'=>"468",'municipio'=> "CERTEGUI",'departamento_id'=> "12"],
            ['id'=>"469",'municipio'=> "CONDOTO",'departamento_id'=> "12"],
            ['id'=>"470",'municipio'=> "EL CARMEN",'departamento_id'=> "12"],
            ['id'=>"471",'municipio'=> "ISTMINA",'departamento_id'=> "12"],
            ['id'=>"472",'municipio'=> "JURADO",'departamento_id'=> "12"],
            ['id'=>"473",'municipio'=> "LITORAL DEL SAN JUAN",'departamento_id'=> "12"],
            ['id'=>"474",'municipio'=> "LLORO",'departamento_id'=> "12"],
            ['id'=>"475",'municipio'=> "MEDIO ATRATO",'departamento_id'=> "12"],
            ['id'=>"476",'municipio'=> "MEDIO BAUDO (BOCA DE PEPE)",'departamento_id'=> "12"],
            ['id'=>"477",'municipio'=> "MEDIO SAN JUAN",'departamento_id'=> "12"],
            ['id'=>"478",'municipio'=> "NOVITA",'departamento_id'=> "12"],
            ['id'=>"479",'municipio'=> "NUQUI",'departamento_id'=> "12"],
            ['id'=>"480",'municipio'=> "QUIBDO",'departamento_id'=> "12"],
            ['id'=>"481",'municipio'=> "RIO IRO",'departamento_id'=> "12"],
            ['id'=>"482",'municipio'=> "RIO QUITO",'departamento_id'=> "12"],
            ['id'=>"483",'municipio'=> "RIOSUCIO",'departamento_id'=> "12"],
            ['id'=>"484",'municipio'=> "SAN JOSE DEL PALMAR",'departamento_id'=> "12"],
            ['id'=>"485",'municipio'=> "SIPI",'departamento_id'=> "12"],
            ['id'=>"486",'municipio'=> "TADO",'departamento_id'=> "12"],
            ['id'=>"487",'municipio'=> "UNGUIA",'departamento_id'=> "12"],
            ['id'=>"488",'municipio'=> "UNIÓN PANAMERICANA",'departamento_id'=> "12"],
            ['id'=>"489",'municipio'=> "AYAPEL",'departamento_id'=> "13"],
            ['id'=>"490",'municipio'=> "BUENAVISTA",'departamento_id'=> "13"],
            ['id'=>"491",'municipio'=> "CANALETE",'departamento_id'=> "13"],
            ['id'=>"492",'municipio'=> "CERETÉ",'departamento_id'=> "13"],
            ['id'=>"493",'municipio'=> "CHIMA",'departamento_id'=> "13"],
            ['id'=>"494",'municipio'=> "CHINÚ",'departamento_id'=> "13"],
            ['id'=>"495",'municipio'=> "CIENAGA DE ORO",'departamento_id'=> "13"],
            ['id'=>"496",'municipio'=> "COTORRA",'departamento_id'=> "13"],
            ['id'=>"497",'municipio'=> "LA APARTADA",'departamento_id'=> "13"],
            ['id'=>"498",'municipio'=> "LORICA",'departamento_id'=> "13"],
            ['id'=>"499",'municipio'=> "LOS CÓRDOBAS",'departamento_id'=> "13"],
            ['id'=>"500",'municipio'=> "MOMIL",'departamento_id'=> "13"],
            ['id'=>"501",'municipio'=> "MONTELÍBANO",'departamento_id'=> "13"],
            ['id'=>"502",'municipio'=> "MONTERÍA",'departamento_id'=> "13"],
            ['id'=>"503",'municipio'=> "MOÑITOS",'departamento_id'=> "13"],
            ['id'=>"504",'municipio'=> "PLANETA RICA",'departamento_id'=> "13"],
            ['id'=>"505",'municipio'=> "PUEBLO NUEVO",'departamento_id'=> "13"],
            ['id'=>"506",'municipio'=> "PUERTO ESCONDIDO",'departamento_id'=> "13"],
            ['id'=>"507",'municipio'=> "PUERTO LIBERTADOR",'departamento_id'=> "13"],
            ['id'=>"508",'municipio'=> "PURÍSIMA",'departamento_id'=> "13"],
            ['id'=>"509",'municipio'=> "SAHAGÚN",'departamento_id'=> "13"],
            ['id'=>"510",'municipio'=> "SAN ANDRÉS SOTAVENTO",'departamento_id'=> "13"],
            ['id'=>"511",'municipio'=> "SAN ANTERO",'departamento_id'=> "13"],
            ['id'=>"512",'municipio'=> "SAN BERNARDO VIENTO",'departamento_id'=> "13"],
            ['id'=>"513",'municipio'=> "SAN CARLOS",'departamento_id'=> "13"],
            ['id'=>"514",'municipio'=> "SAN PELAYO",'departamento_id'=> "13"],
            ['id'=>"515",'municipio'=> "TIERRALTA",'departamento_id'=> "13"],
            ['id'=>"516",'municipio'=> "VALENCIA",'departamento_id'=> "13"],
            ['id'=>"517",'municipio'=> "AGUA DE DIOS",'departamento_id'=> "14"],
            ['id'=>"518",'municipio'=> "ALBAN",'departamento_id'=> "14"],
            ['id'=>"519",'municipio'=> "ANAPOIMA",'departamento_id'=> "14"],
            ['id'=>"520",'municipio'=> "ANOLAIMA",'departamento_id'=> "14"],
            ['id'=>"521",'municipio'=> "ARBELAEZ",'departamento_id'=> "14"],
            ['id'=>"522",'municipio'=> "BELTRÁN",'departamento_id'=> "14"],
            ['id'=>"523",'municipio'=> "BITUIMA",'departamento_id'=> "14"],
            ['id'=>"524",'municipio'=> "BOGOTÁ DC",'departamento_id'=> "14"],
            ['id'=>"525",'municipio'=> "BOJACÁ",'departamento_id'=> "14"],
            ['id'=>"526",'municipio'=> "CABRERA",'departamento_id'=> "14"],
            ['id'=>"527",'municipio'=> "CACHIPAY",'departamento_id'=> "14"],
            ['id'=>"528",'municipio'=> "CAJICÁ",'departamento_id'=> "14"],
            ['id'=>"529",'municipio'=> "CAPARRAPÍ",'departamento_id'=> "14"],
            ['id'=>"530",'municipio'=> "CAQUEZA",'departamento_id'=> "14"],
            ['id'=>"531",'municipio'=> "CARMEN DE CARUPA",'departamento_id'=> "14"],
            ['id'=>"532",'municipio'=> "CHAGUANÍ",'departamento_id'=> "14"],
            ['id'=>"533",'municipio'=> "CHIA",'departamento_id'=> "14"],
            ['id'=>"534",'municipio'=> "CHIPAQUE",'departamento_id'=> "14"],
            ['id'=>"535",'municipio'=> "CHOACHÍ",'departamento_id'=> "14"],
            ['id'=>"536",'municipio'=> "CHOCONTÁ",'departamento_id'=> "14"],
            ['id'=>"537",'municipio'=> "COGUA",'departamento_id'=> "14"],
            ['id'=>"538",'municipio'=> "COTA",'departamento_id'=> "14"],
            ['id'=>"539",'municipio'=> "CUCUNUBÁ",'departamento_id'=> "14"],
            ['id'=>"540",'municipio'=> "EL COLEGIO",'departamento_id'=> "14"],
            ['id'=>"541",'municipio'=> "EL PEÑÓN",'departamento_id'=> "14"],
            ['id'=>"542",'municipio'=> "EL ROSAL1",'departamento_id'=> "14"],
            ['id'=>"543",'municipio'=> "FACATATIVA",'departamento_id'=> "14"],
            ['id'=>"544",'municipio'=> "FÓMEQUE",'departamento_id'=> "14"],
            ['id'=>"545",'municipio'=> "FOSCA",'departamento_id'=> "14"],
            ['id'=>"546",'municipio'=> "FUNZA",'departamento_id'=> "14"],
            ['id'=>"547",'municipio'=> "FÚQUENE",'departamento_id'=> "14"],
            ['id'=>"548",'municipio'=> "FUSAGASUGA",'departamento_id'=> "14"],
            ['id'=>"549",'municipio'=> "GACHALÁ",'departamento_id'=> "14"],
            ['id'=>"550",'municipio'=> "GACHANCIPÁ",'departamento_id'=> "14"],
            ['id'=>"551",'municipio'=> "GACHETA",'departamento_id'=> "14"],
            ['id'=>"552",'municipio'=> "GAMA",'departamento_id'=> "14"],
            ['id'=>"553",'municipio'=> "GIRARDOT",'departamento_id'=> "14"],
            ['id'=>"554",'municipio'=> "GRANADA2",'departamento_id'=> "14"],
            ['id'=>"555",'municipio'=> "GUACHETÁ",'departamento_id'=> "14"],
            ['id'=>"556",'municipio'=> "GUADUAS",'departamento_id'=> "14"],
            ['id'=>"557",'municipio'=> "GUASCA",'departamento_id'=> "14"],
            ['id'=>"558",'municipio'=> "GUATAQUÍ",'departamento_id'=> "14"],
            ['id'=>"559",'municipio'=> "GUATAVITA",'departamento_id'=> "14"],
            ['id'=>"560",'municipio'=> "GUAYABAL DE SIQUIMA",'departamento_id'=> "14"],
            ['id'=>"561",'municipio'=> "GUAYABETAL",'departamento_id'=> "14"],
            ['id'=>"562",'municipio'=> "GUTIÉRREZ",'departamento_id'=> "14"],
            ['id'=>"563",'municipio'=> "JERUSALÉN",'departamento_id'=> "14"],
            ['id'=>"564",'municipio'=> "JUNÍN",'departamento_id'=> "14"],
            ['id'=>"565",'municipio'=> "LA CALERA",'departamento_id'=> "14"],
            ['id'=>"566",'municipio'=> "LA MESA",'departamento_id'=> "14"],
            ['id'=>"567",'municipio'=> "LA PALMA",'departamento_id'=> "14"],
            ['id'=>"568",'municipio'=> "LA PEÑA",'departamento_id'=> "14"],
            ['id'=>"569",'municipio'=> "LA VEGA",'departamento_id'=> "14"],
            ['id'=>"570",'municipio'=> "LENGUAZAQUE",'departamento_id'=> "14"],
            ['id'=>"571",'municipio'=> "MACHETÁ",'departamento_id'=> "14"],
            ['id'=>"572",'municipio'=> "MADRID",'departamento_id'=> "14"],
            ['id'=>"573",'municipio'=> "MANTA",'departamento_id'=> "14"],
            ['id'=>"574",'municipio'=> "MEDINA",'departamento_id'=> "14"],
            ['id'=>"575",'municipio'=> "MOSQUERA",'departamento_id'=> "14"],
            ['id'=>"576",'municipio'=> "NARIÑO",'departamento_id'=> "14"],
            ['id'=>"577",'municipio'=> "NEMOCÓN",'departamento_id'=> "14"],
            ['id'=>"578",'municipio'=> "NILO",'departamento_id'=> "14"],
            ['id'=>"579",'municipio'=> "NIMAIMA",'departamento_id'=> "14"],
            ['id'=>"580",'municipio'=> "NOCAIMA",'departamento_id'=> "14"],
            ['id'=>"581",'municipio'=> "OSPINA PÉREZ",'departamento_id'=> "14"],
            ['id'=>"582",'municipio'=> "PACHO",'departamento_id'=> "14"],
            ['id'=>"583",'municipio'=> "PAIME",'departamento_id'=> "14"],
            ['id'=>"584",'municipio'=> "PANDI",'departamento_id'=> "14"],
            ['id'=>"585",'municipio'=> "PARATEBUENO",'departamento_id'=> "14"],
            ['id'=>"586",'municipio'=> "PASCA",'departamento_id'=> "14"],
            ['id'=>"587",'municipio'=> "PUERTO SALGAR",'departamento_id'=> "14"],
            ['id'=>"588",'municipio'=> "PULÍ",'departamento_id'=> "14"],
            ['id'=>"589",'municipio'=> "QUEBRADANEGRA",'departamento_id'=> "14"],
            ['id'=>"590",'municipio'=> "QUETAME",'departamento_id'=> "14"],
            ['id'=>"591",'municipio'=> "QUIPILE",'departamento_id'=> "14"],
            ['id'=>"592",'municipio'=> "RAFAEL REYES",'departamento_id'=> "14"],
            ['id'=>"593",'municipio'=> "RICAURTE",'departamento_id'=> "14"],
            ['id'=>"594",'municipio'=> "SAN  ANTONIO DEL  TEQUENDAMA",'departamento_id'=> "14"],
            ['id'=>"595",'municipio'=> "SAN BERNARDO",'departamento_id'=> "14"],
            ['id'=>"596",'municipio'=> "SAN CAYETANO",'departamento_id'=> "14"],
            ['id'=>"597",'municipio'=> "SAN FRANCISCO",'departamento_id'=> "14"],
            ['id'=>"598",'municipio'=> "SAN JUAN DE RIOSECO",'departamento_id'=> "14"],
            ['id'=>"599",'municipio'=> "SASAIMA",'departamento_id'=> "14"],
            ['id'=>"600",'municipio'=> "SESQUILÉ",'departamento_id'=> "14"],
            ['id'=>"601",'municipio'=> "SIBATÉ",'departamento_id'=> "14"],
            ['id'=>"602",'municipio'=> "SILVANIA",'departamento_id'=> "14"],
            ['id'=>"603",'municipio'=> "SIMIJACA",'departamento_id'=> "14"],
            ['id'=>"604",'municipio'=> "SOACHA",'departamento_id'=> "14"],
            ['id'=>"605",'municipio'=> "SOPO",'departamento_id'=> "14"],
            ['id'=>"606",'municipio'=> "SUBACHOQUE",'departamento_id'=> "14"],
            ['id'=>"607",'municipio'=> "SUESCA",'departamento_id'=> "14"],
            ['id'=>"608",'municipio'=> "SUPATÁ",'departamento_id'=> "14"],
            ['id'=>"609",'municipio'=> "SUSA",'departamento_id'=> "14"],
            ['id'=>"610",'municipio'=> "SUTATAUSA",'departamento_id'=> "14"],
            ['id'=>"611",'municipio'=> "TABIO",'departamento_id'=> "14"],
            ['id'=>"612",'municipio'=> "TAUSA",'departamento_id'=> "14"],
            ['id'=>"613",'municipio'=> "TENA",'departamento_id'=> "14"],
            ['id'=>"614",'municipio'=> "TENJO",'departamento_id'=> "14"],
            ['id'=>"615",'municipio'=> "TIBACUY",'departamento_id'=> "14"],
            ['id'=>"616",'municipio'=> "TIBIRITA",'departamento_id'=> "14"],
            ['id'=>"617",'municipio'=> "TOCAIMA",'departamento_id'=> "14"],
            ['id'=>"618",'municipio'=> "TOCANCIPÁ",'departamento_id'=> "14"],
            ['id'=>"619",'municipio'=> "TOPAIPÍ",'departamento_id'=> "14"],
            ['id'=>"620",'municipio'=> "UBALÁ",'departamento_id'=> "14"],
            ['id'=>"621",'municipio'=> "UBAQUE",'departamento_id'=> "14"],
            ['id'=>"622",'municipio'=> "UBATÉ",'departamento_id'=> "14"],
            ['id'=>"623",'municipio'=> "UNE",'departamento_id'=> "14"],
            ['id'=>"624",'municipio'=> "UTICA",'departamento_id'=> "14"],
            ['id'=>"625",'municipio'=> "VERGARA",'departamento_id'=> "14"],
            ['id'=>"626",'municipio'=> "VIANI",'departamento_id'=> "14"],
            ['id'=>"627",'municipio'=> "VILLA GOMEZ",'departamento_id'=> "14"],
            ['id'=>"628",'municipio'=> "VILLA PINZÓN",'departamento_id'=> "14"],
            ['id'=>"629",'municipio'=> "VILLETA",'departamento_id'=> "14"],
            ['id'=>"630",'municipio'=> "VIOTA",'departamento_id'=> "14"],
            ['id'=>"631",'municipio'=> "YACOPÍ",'departamento_id'=> "14"],
            ['id'=>"632",'municipio'=> "ZIPACÓN",'departamento_id'=> "14"],
            ['id'=>"633",'municipio'=> "ZIPAQUIRÁ",'departamento_id'=> "14"],
            ['id'=>"634",'municipio'=> "BARRANCO MINAS",'departamento_id'=> "15"],
            ['id'=>"635",'municipio'=> "CACAHUAL",'departamento_id'=> "15"],
            ['id'=>"636",'municipio'=> "INÍRIDA",'departamento_id'=> "15"],
            ['id'=>"637",'municipio'=> "LA GUADALUPE",'departamento_id'=> "15"],
            ['id'=>"638",'municipio'=> "MAPIRIPANA",'departamento_id'=> "15"],
            ['id'=>"639",'municipio'=> "MORICHAL",'departamento_id'=> "15"],
            ['id'=>"640",'municipio'=> "PANA PANA",'departamento_id'=> "15"],
            ['id'=>"641",'municipio'=> "PUERTO COLOMBIA",'departamento_id'=> "15"],
            ['id'=>"642",'municipio'=> "SAN FELIPE",'departamento_id'=> "15"],
            ['id'=>"643",'municipio'=> "CALAMAR",'departamento_id'=> "16"],
            ['id'=>"644",'municipio'=> "EL RETORNO",'departamento_id'=> "16"],
            ['id'=>"645",'municipio'=> "MIRAFLOREZ",'departamento_id'=> "16"],
            ['id'=>"646",'municipio'=> "SAN JOSÉ DEL GUAVIARE",'departamento_id'=> "16"],
            ['id'=>"647",'municipio'=> "ACEVEDO",'departamento_id'=> "17"],
            ['id'=>"648",'municipio'=> "AGRADO",'departamento_id'=> "17"],
            ['id'=>"649",'municipio'=> "AIPE",'departamento_id'=> "17"],
            ['id'=>"650",'municipio'=> "ALGECIRAS",'departamento_id'=> "17"],
            ['id'=>"651",'municipio'=> "ALTAMIRA",'departamento_id'=> "17"],
            ['id'=>"652",'municipio'=> "BARAYA",'departamento_id'=> "17"],
            ['id'=>"653",'municipio'=> "CAMPO ALEGRE",'departamento_id'=> "17"],
            ['id'=>"654",'municipio'=> "COLOMBIA",'departamento_id'=> "17"],
            ['id'=>"655",'municipio'=> "ELIAS",'departamento_id'=> "17"],
            ['id'=>"656",'municipio'=> "GARZÓN",'departamento_id'=> "17"],
            ['id'=>"657",'municipio'=> "GIGANTE",'departamento_id'=> "17"],
            ['id'=>"658",'municipio'=> "GUADALUPE",'departamento_id'=> "17"],
            ['id'=>"659",'municipio'=> "HOBO",'departamento_id'=> "17"],
            ['id'=>"660",'municipio'=> "IQUIRA",'departamento_id'=> "17"],
            ['id'=>"661",'municipio'=> "ISNOS",'departamento_id'=> "17"],
            ['id'=>"662",'municipio'=> "LA ARGENTINA",'departamento_id'=> "17"],
            ['id'=>"663",'municipio'=> "LA PLATA",'departamento_id'=> "17"],
            ['id'=>"664",'municipio'=> "NATAGA",'departamento_id'=> "17"],
            ['id'=>"665",'municipio'=> "NEIVA",'departamento_id'=> "17"],
            ['id'=>"666",'municipio'=> "OPORAPA",'departamento_id'=> "17"],
            ['id'=>"667",'municipio'=> "PAICOL",'departamento_id'=> "17"],
            ['id'=>"668",'municipio'=> "PALERMO",'departamento_id'=> "17"],
            ['id'=>"669",'municipio'=> "PALESTINA",'departamento_id'=> "17"],
            ['id'=>"670",'municipio'=> "PITAL",'departamento_id'=> "17"],
            ['id'=>"671",'municipio'=> "PITALITO",'departamento_id'=> "17"],
            ['id'=>"672",'municipio'=> "RIVERA",'departamento_id'=> "17"],
            ['id'=>"673",'municipio'=> "SALADO BLANCO",'departamento_id'=> "17"],
            ['id'=>"674",'municipio'=> "SAN AGUSTÍN",'departamento_id'=> "17"],
            ['id'=>"675",'municipio'=> "SANTA MARIA",'departamento_id'=> "17"],
            ['id'=>"676",'municipio'=> "SUAZA",'departamento_id'=> "17"],
            ['id'=>"677",'municipio'=> "TARQUI",'departamento_id'=> "17"],
            ['id'=>"678",'municipio'=> "TELLO",'departamento_id'=> "17"],
            ['id'=>"679",'municipio'=> "TERUEL",'departamento_id'=> "17"],
            ['id'=>"680",'municipio'=> "TESALIA",'departamento_id'=> "17"],
            ['id'=>"681",'municipio'=> "TIMANA",'departamento_id'=> "17"],
            ['id'=>"682",'municipio'=> "VILLAVIEJA",'departamento_id'=> "17"],
            ['id'=>"683",'municipio'=> "YAGUARA",'departamento_id'=> "17"],
            ['id'=>"684",'municipio'=> "ALBANIA",'departamento_id'=> "18"],
            ['id'=>"685",'municipio'=> "BARRANCAS",'departamento_id'=> "18"],
            ['id'=>"686",'municipio'=> "DIBULLA",'departamento_id'=> "18"],
            ['id'=>"687",'municipio'=> "DISTRACCIÓN",'departamento_id'=> "18"],
            ['id'=>"688",'municipio'=> "EL MOLINO",'departamento_id'=> "18"],
            ['id'=>"689",'municipio'=> "FONSECA",'departamento_id'=> "18"],
            ['id'=>"690",'municipio'=> "HATO NUEVO",'departamento_id'=> "18"],
            ['id'=>"691",'municipio'=> "LA JAGUA DEL PILAR",'departamento_id'=> "18"],
            ['id'=>"692",'municipio'=> "MAICAO",'departamento_id'=> "18"],
            ['id'=>"693",'municipio'=> "MANAURE",'departamento_id'=> "18"],
            ['id'=>"694",'municipio'=> "RIOHACHA",'departamento_id'=> "18"],
            ['id'=>"695",'municipio'=> "SAN JUAN DEL CESAR",'departamento_id'=> "18"],
            ['id'=>"696",'municipio'=> "URIBIA",'departamento_id'=> "18"],
            ['id'=>"697",'municipio'=> "URUMITA",'departamento_id'=> "18"],
            ['id'=>"698",'municipio'=> "VILLANUEVA",'departamento_id'=> "18"],
            ['id'=>"699",'municipio'=> "ALGARROBO",'departamento_id'=> "19"],
            ['id'=>"700",'municipio'=> "ARACATACA",'departamento_id'=> "19"],
            ['id'=>"701",'municipio'=> "ARIGUANI",'departamento_id'=> "19"],
            ['id'=>"702",'municipio'=> "CERRO SAN ANTONIO",'departamento_id'=> "19"],
            ['id'=>"703",'municipio'=> "CHIVOLO",'departamento_id'=> "19"],
            ['id'=>"704",'municipio'=> "CIENAGA",'departamento_id'=> "19"],
            ['id'=>"705",'municipio'=> "CONCORDIA",'departamento_id'=> "19"],
            ['id'=>"706",'municipio'=> "EL BANCO",'departamento_id'=> "19"],
            ['id'=>"707",'municipio'=> "EL PIÑON",'departamento_id'=> "19"],
            ['id'=>"708",'municipio'=> "EL RETEN",'departamento_id'=> "19"],
            ['id'=>"709",'municipio'=> "FUNDACION",'departamento_id'=> "19"],
            ['id'=>"710",'municipio'=> "GUAMAL",'departamento_id'=> "19"],
            ['id'=>"711",'municipio'=> "NUEVA GRANADA",'departamento_id'=> "19"],
            ['id'=>"712",'municipio'=> "PEDRAZA",'departamento_id'=> "19"],
            ['id'=>"713",'municipio'=> "PIJIÑO DEL CARMEN",'departamento_id'=> "19"],
            ['id'=>"714",'municipio'=> "PIVIJAY",'departamento_id'=> "19"],
            ['id'=>"715",'municipio'=> "PLATO",'departamento_id'=> "19"],
            ['id'=>"716",'municipio'=> "PUEBLO VIEJO",'departamento_id'=> "19"],
            ['id'=>"717",'municipio'=> "REMOLINO",'departamento_id'=> "19"],
            ['id'=>"718",'municipio'=> "SABANAS DE SAN ANGEL",'departamento_id'=> "19"],
            ['id'=>"719",'municipio'=> "SALAMINA",'departamento_id'=> "19"],
            ['id'=>"720",'municipio'=> "SAN SEBASTIAN DE BUENAVISTA",'departamento_id'=> "19"],
            ['id'=>"721",'municipio'=> "SAN ZENON",'departamento_id'=> "19"],
            ['id'=>"722",'municipio'=> "SANTA ANA",'departamento_id'=> "19"],
            ['id'=>"723",'municipio'=> "SANTA BARBARA DE PINTO",'departamento_id'=> "19"],
            ['id'=>"724",'municipio'=> "SANTA MARTA",'departamento_id'=> "19"],
            ['id'=>"725",'municipio'=> "SITIONUEVO",'departamento_id'=> "19"],
            ['id'=>"726",'municipio'=> "TENERIFE",'departamento_id'=> "19"],
            ['id'=>"727",'municipio'=> "ZAPAYAN",'departamento_id'=> "19"],
            ['id'=>"728",'municipio'=> "ZONA BANANERA",'departamento_id'=> "19"],
            ['id'=>"729",'municipio'=> "ACACIAS",'departamento_id'=> "20"],
            ['id'=>"730",'municipio'=> "BARRANCA DE UPIA",'departamento_id'=> "20"],
            ['id'=>"731",'municipio'=> "CABUYARO",'departamento_id'=> "20"],
            ['id'=>"732",'municipio'=> "CASTILLA LA NUEVA",'departamento_id'=> "20"],
            ['id'=>"733",'municipio'=> "CUBARRAL",'departamento_id'=> "20"],
            ['id'=>"734",'municipio'=> "CUMARAL",'departamento_id'=> "20"],
            ['id'=>"735",'municipio'=> "EL CALVARIO",'departamento_id'=> "20"],
            ['id'=>"736",'municipio'=> "EL CASTILLO",'departamento_id'=> "20"],
            ['id'=>"737",'municipio'=> "EL DORADO",'departamento_id'=> "20"],
            ['id'=>"738",'municipio'=> "FUENTE DE ORO",'departamento_id'=> "20"],
            ['id'=>"739",'municipio'=> "GRANADA",'departamento_id'=> "20"],
            ['id'=>"740",'municipio'=> "GUAMAL",'departamento_id'=> "20"],
            ['id'=>"741",'municipio'=> "LA MACARENA",'departamento_id'=> "20"],
            ['id'=>"742",'municipio'=> "LA URIBE",'departamento_id'=> "20"],
            ['id'=>"743",'municipio'=> "LEJANÍAS",'departamento_id'=> "20"],
            ['id'=>"744",'municipio'=> "MAPIRIPÁN",'departamento_id'=> "20"],
            ['id'=>"745",'municipio'=> "MESETAS",'departamento_id'=> "20"],
            ['id'=>"746",'municipio'=> "PUERTO CONCORDIA",'departamento_id'=> "20"],
            ['id'=>"747",'municipio'=> "PUERTO GAITÁN",'departamento_id'=> "20"],
            ['id'=>"748",'municipio'=> "PUERTO LLERAS",'departamento_id'=> "20"],
            ['id'=>"749",'municipio'=> "PUERTO LÓPEZ",'departamento_id'=> "20"],
            ['id'=>"750",'municipio'=> "PUERTO RICO",'departamento_id'=> "20"],
            ['id'=>"751",'municipio'=> "RESTREPO",'departamento_id'=> "20"],
            ['id'=>"752",'municipio'=> "SAN  JUAN DE ARAMA",'departamento_id'=> "20"],
            ['id'=>"753",'municipio'=> "SAN CARLOS GUAROA",'departamento_id'=> "20"],
            ['id'=>"754",'municipio'=> "SAN JUANITO",'departamento_id'=> "20"],
            ['id'=>"755",'municipio'=> "SAN MARTÍN",'departamento_id'=> "20"],
            ['id'=>"756",'municipio'=> "VILLAVICENCIO",'departamento_id'=> "20"],
            ['id'=>"757",'municipio'=> "VISTA HERMOSA",'departamento_id'=> "20"],
            ['id'=>"758",'municipio'=> "ALBAN",'departamento_id'=> "21"],
            ['id'=>"759",'municipio'=> "ALDAÑA",'departamento_id'=> "21"],
            ['id'=>"760",'municipio'=> "ANCUYA",'departamento_id'=> "21"],
            ['id'=>"761",'municipio'=> "ARBOLEDA",'departamento_id'=> "21"],
            ['id'=>"762",'municipio'=> "BARBACOAS",'departamento_id'=> "21"],
            ['id'=>"763",'municipio'=> "BELEN",'departamento_id'=> "21"],
            ['id'=>"764",'municipio'=> "BUESACO",'departamento_id'=> "21"],
            ['id'=>"765",'municipio'=> "CHACHAGUI",'departamento_id'=> "21"],
            ['id'=>"766",'municipio'=> "COLON (GENOVA)",'departamento_id'=> "21"],
            ['id'=>"767",'municipio'=> "CONSACA",'departamento_id'=> "21"],
            ['id'=>"768",'municipio'=> "CONTADERO",'departamento_id'=> "21"],
            ['id'=>"769",'municipio'=> "CORDOBA",'departamento_id'=> "21"],
            ['id'=>"770",'municipio'=> "CUASPUD",'departamento_id'=> "21"],
            ['id'=>"771",'municipio'=> "CUMBAL",'departamento_id'=> "21"],
            ['id'=>"772",'municipio'=> "CUMBITARA",'departamento_id'=> "21"],
            ['id'=>"773",'municipio'=> "EL CHARCO",'departamento_id'=> "21"],
            ['id'=>"774",'municipio'=> "EL PEÑOL",'departamento_id'=> "21"],
            ['id'=>"775",'municipio'=> "EL ROSARIO",'departamento_id'=> "21"],
            ['id'=>"776",'municipio'=> "EL TABLÓN",'departamento_id'=> "21"],
            ['id'=>"777",'municipio'=> "EL TAMBO",'departamento_id'=> "21"],
            ['id'=>"778",'municipio'=> "FUNES",'departamento_id'=> "21"],
            ['id'=>"779",'municipio'=> "GUACHUCAL",'departamento_id'=> "21"],
            ['id'=>"780",'municipio'=> "GUAITARILLA",'departamento_id'=> "21"],
            ['id'=>"781",'municipio'=> "GUALMATAN",'departamento_id'=> "21"],
            ['id'=>"782",'municipio'=> "ILES",'departamento_id'=> "21"],
            ['id'=>"783",'municipio'=> "IMUES",'departamento_id'=> "21"],
            ['id'=>"784",'municipio'=> "IPIALES",'departamento_id'=> "21"],
            ['id'=>"785",'municipio'=> "LA CRUZ",'departamento_id'=> "21"],
            ['id'=>"786",'municipio'=> "LA FLORIDA",'departamento_id'=> "21"],
            ['id'=>"787",'municipio'=> "LA LLANADA",'departamento_id'=> "21"],
            ['id'=>"788",'municipio'=> "LA TOLA",'departamento_id'=> "21"],
            ['id'=>"789",'municipio'=> "LA UNION",'departamento_id'=> "21"],
            ['id'=>"790",'municipio'=> "LEIVA",'departamento_id'=> "21"],
            ['id'=>"791",'municipio'=> "LINARES",'departamento_id'=> "21"],
            ['id'=>"792",'municipio'=> "LOS ANDES",'departamento_id'=> "21"],
            ['id'=>"793",'municipio'=> "MAGUI",'departamento_id'=> "21"],
            ['id'=>"794",'municipio'=> "MALLAMA",'departamento_id'=> "21"],
            ['id'=>"795",'municipio'=> "MOSQUEZA",'departamento_id'=> "21"],
            ['id'=>"796",'municipio'=> "NARIÑO",'departamento_id'=> "21"],
            ['id'=>"797",'municipio'=> "OLAYA HERRERA",'departamento_id'=> "21"],
            ['id'=>"798",'municipio'=> "OSPINA",'departamento_id'=> "21"],
            ['id'=>"799",'municipio'=> "PASTO",'departamento_id'=> "21"],
            ['id'=>"800",'municipio'=> "PIZARRO",'departamento_id'=> "21"],
            ['id'=>"801",'municipio'=> "POLICARPA",'departamento_id'=> "21"],
            ['id'=>"802",'municipio'=> "POTOSI",'departamento_id'=> "21"],
            ['id'=>"803",'municipio'=> "PROVIDENCIA",'departamento_id'=> "21"],
            ['id'=>"804",'municipio'=> "PUERRES",'departamento_id'=> "21"],
            ['id'=>"805",'municipio'=> "PUPIALES",'departamento_id'=> "21"],
            ['id'=>"806",'municipio'=> "RICAURTE",'departamento_id'=> "21"],
            ['id'=>"807",'municipio'=> "ROBERTO PAYAN",'departamento_id'=> "21"],
            ['id'=>"808",'municipio'=> "SAMANIEGO",'departamento_id'=> "21"],
            ['id'=>"809",'municipio'=> "SAN BERNARDO",'departamento_id'=> "21"],
            ['id'=>"810",'municipio'=> "SAN LORENZO",'departamento_id'=> "21"],
            ['id'=>"811",'municipio'=> "SAN PABLO",'departamento_id'=> "21"],
            ['id'=>"812",'municipio'=> "SAN PEDRO DE CARTAGO",'departamento_id'=> "21"],
            ['id'=>"813",'municipio'=> "SANDONA",'departamento_id'=> "21"],
            ['id'=>"814",'municipio'=> "SANTA BARBARA",'departamento_id'=> "21"],
            ['id'=>"815",'municipio'=> "SANTACRUZ",'departamento_id'=> "21"],
            ['id'=>"816",'municipio'=> "SAPUYES",'departamento_id'=> "21"],
            ['id'=>"817",'municipio'=> "TAMINANGO",'departamento_id'=> "21"],
            ['id'=>"818",'municipio'=> "TANGUA",'departamento_id'=> "21"],
            ['id'=>"819",'municipio'=> "TUMACO",'departamento_id'=> "21"],
            ['id'=>"820",'municipio'=> "TUQUERRES",'departamento_id'=> "21"],
            ['id'=>"821",'municipio'=> "YACUANQUER",'departamento_id'=> "21"],
            ['id'=>"822",'municipio'=> "ABREGO",'departamento_id'=> "22"],
            ['id'=>"823",'municipio'=> "ARBOLEDAS",'departamento_id'=> "22"],
            ['id'=>"824",'municipio'=> "BOCHALEMA",'departamento_id'=> "22"],
            ['id'=>"825",'municipio'=> "BUCARASICA",'departamento_id'=> "22"],
            ['id'=>"826",'municipio'=> "CÁCHIRA",'departamento_id'=> "22"],
            ['id'=>"827",'municipio'=> "CÁCOTA",'departamento_id'=> "22"],
            ['id'=>"828",'municipio'=> "CHINÁCOTA",'departamento_id'=> "22"],
            ['id'=>"829",'municipio'=> "CHITAGÁ",'departamento_id'=> "22"],
            ['id'=>"830",'municipio'=> "CONVENCIÓN",'departamento_id'=> "22"],
            ['id'=>"831",'municipio'=> "CÚCUTA",'departamento_id'=> "22"],
            ['id'=>"832",'municipio'=> "CUCUTILLA",'departamento_id'=> "22"],
            ['id'=>"833",'municipio'=> "DURANIA",'departamento_id'=> "22"],
            ['id'=>"834",'municipio'=> "EL CARMEN",'departamento_id'=> "22"],
            ['id'=>"835",'municipio'=> "EL TARRA",'departamento_id'=> "22"],
            ['id'=>"836",'municipio'=> "EL ZULIA",'departamento_id'=> "22"],
            ['id'=>"837",'municipio'=> "GRAMALOTE",'departamento_id'=> "22"],
            ['id'=>"838",'municipio'=> "HACARI",'departamento_id'=> "22"],
            ['id'=>"839",'municipio'=> "HERRÁN",'departamento_id'=> "22"],
            ['id'=>"840",'municipio'=> "LA ESPERANZA",'departamento_id'=> "22"],
            ['id'=>"841",'municipio'=> "LA PLAYA",'departamento_id'=> "22"],
            ['id'=>"842",'municipio'=> "LABATECA",'departamento_id'=> "22"],
            ['id'=>"843",'municipio'=> "LOS PATIOS",'departamento_id'=> "22"],
            ['id'=>"844",'municipio'=> "LOURDES",'departamento_id'=> "22"],
            ['id'=>"845",'municipio'=> "MUTISCUA",'departamento_id'=> "22"],
            ['id'=>"846",'municipio'=> "OCAÑA",'departamento_id'=> "22"],
            ['id'=>"847",'municipio'=> "PAMPLONA",'departamento_id'=> "22"],
            ['id'=>"848",'municipio'=> "PAMPLONITA",'departamento_id'=> "22"],
            ['id'=>"849",'municipio'=> "PUERTO SANTANDER",'departamento_id'=> "22"],
            ['id'=>"850",'municipio'=> "RAGONVALIA",'departamento_id'=> "22"],
            ['id'=>"851",'municipio'=> "SALAZAR",'departamento_id'=> "22"],
            ['id'=>"852",'municipio'=> "SAN CALIXTO",'departamento_id'=> "22"],
            ['id'=>"853",'municipio'=> "SAN CAYETANO",'departamento_id'=> "22"],
            ['id'=>"854",'municipio'=> "SANTIAGO",'departamento_id'=> "22"],
            ['id'=>"855",'municipio'=> "SARDINATA",'departamento_id'=> "22"],
            ['id'=>"856",'municipio'=> "SILOS",'departamento_id'=> "22"],
            ['id'=>"857",'municipio'=> "TEORAMA",'departamento_id'=> "22"],
            ['id'=>"858",'municipio'=> "TIBÚ",'departamento_id'=> "22"],
            ['id'=>"859",'municipio'=> "TOLEDO",'departamento_id'=> "22"],
            ['id'=>"860",'municipio'=> "VILLA CARO",'departamento_id'=> "22"],
            ['id'=>"861",'municipio'=> "VILLA DEL ROSARIO",'departamento_id'=> "22"],
            ['id'=>"862",'municipio'=> "COLÓN",'departamento_id'=> "23"],
            ['id'=>"863",'municipio'=> "MOCOA",'departamento_id'=> "23"],
            ['id'=>"864",'municipio'=> "ORITO",'departamento_id'=> "23"],
            ['id'=>"865",'municipio'=> "PUERTO ASÍS",'departamento_id'=> "23"],
            ['id'=>"866",'municipio'=> "PUERTO CAYCEDO",'departamento_id'=> "23"],
            ['id'=>"867",'municipio'=> "PUERTO GUZMÁN",'departamento_id'=> "23"],
            ['id'=>"868",'municipio'=> "PUERTO LEGUÍZAMO",'departamento_id'=> "23"],
            ['id'=>"869",'municipio'=> "SAN FRANCISCO",'departamento_id'=> "23"],
            ['id'=>"870",'municipio'=> "SAN MIGUEL",'departamento_id'=> "23"],
            ['id'=>"871",'municipio'=> "SANTIAGO",'departamento_id'=> "23"],
            ['id'=>"872",'municipio'=> "SIBUNDOY",'departamento_id'=> "23"],
            ['id'=>"873",'municipio'=> "VALLE DEL GUAMUEZ",'departamento_id'=> "23"],
            ['id'=>"874",'municipio'=> "VILLAGARZÓN",'departamento_id'=> "23"],
            ['id'=>"875",'municipio'=> "ARMENIA",'departamento_id'=> "24"],
            ['id'=>"876",'municipio'=> "BUENAVISTA",'departamento_id'=> "24"],
            ['id'=>"877",'municipio'=> "CALARCÁ",'departamento_id'=> "24"],
            ['id'=>"878",'municipio'=> "CIRCASIA",'departamento_id'=> "24"],
            ['id'=>"879",'municipio'=> "CÓRDOBA",'departamento_id'=> "24"],
            ['id'=>"880",'municipio'=> "FILANDIA",'departamento_id'=> "24"],
            ['id'=>"881",'municipio'=> "GÉNOVA",'departamento_id'=> "24"],
            ['id'=>"882",'municipio'=> "LA TEBAIDA",'departamento_id'=> "24"],
            ['id'=>"883",'municipio'=> "MONTENEGRO",'departamento_id'=> "24"],
            ['id'=>"884",'municipio'=> "PIJAO",'departamento_id'=> "24"],
            ['id'=>"885",'municipio'=> "QUIMBAYA",'departamento_id'=> "24"],
            ['id'=>"886",'municipio'=> "SALENTO",'departamento_id'=> "24"],
            ['id'=>"887",'municipio'=> "APIA",'departamento_id'=> "25"],
            ['id'=>"888",'municipio'=> "BALBOA",'departamento_id'=> "25"],
            ['id'=>"889",'municipio'=> "BELÉN DE UMBRÍA",'departamento_id'=> "25"],
            ['id'=>"890",'municipio'=> "DOS QUEBRADAS",'departamento_id'=> "25"],
            ['id'=>"891",'municipio'=> "GUATICA",'departamento_id'=> "25"],
            ['id'=>"892",'municipio'=> "LA CELIA",'departamento_id'=> "25"],
            ['id'=>"893",'municipio'=> "LA VIRGINIA",'departamento_id'=> "25"],
            ['id'=>"894",'municipio'=> "MARSELLA",'departamento_id'=> "25"],
            ['id'=>"895",'municipio'=> "MISTRATO",'departamento_id'=> "25"],
            ['id'=>"896",'municipio'=> "PEREIRA",'departamento_id'=> "25"],
            ['id'=>"897",'municipio'=> "PUEBLO RICO",'departamento_id'=> "25"],
            ['id'=>"898",'municipio'=> "QUINCHÍA",'departamento_id'=> "25"],
            ['id'=>"899",'municipio'=> "SANTA ROSA DE CABAL",'departamento_id'=> "25"],
            ['id'=>"900",'municipio'=> "SANTUARIO",'departamento_id'=> "25"],
            ['id'=>"901",'municipio'=> "PROVIDENCIA",'departamento_id'=> "26"],
            ['id'=>"902",'municipio'=> "SAN ANDRES",'departamento_id'=> "26"],
            ['id'=>"903",'municipio'=> "SANTA CATALINA",'departamento_id'=> "26"],
            ['id'=>"904",'municipio'=> "AGUADA",'departamento_id'=> "27"],
            ['id'=>"905",'municipio'=> "ALBANIA",'departamento_id'=> "27"],
            ['id'=>"906",'municipio'=> "ARATOCA",'departamento_id'=> "27"],
            ['id'=>"907",'municipio'=> "BARBOSA",'departamento_id'=> "27"],
            ['id'=>"908",'municipio'=> "BARICHARA",'departamento_id'=> "27"],
            ['id'=>"909",'municipio'=> "BARRANCABERMEJA",'departamento_id'=> "27"],
            ['id'=>"910",'municipio'=> "BETULIA",'departamento_id'=> "27"],
            ['id'=>"911",'municipio'=> "BOLÍVAR",'departamento_id'=> "27"],
            ['id'=>"912",'municipio'=> "BUCARAMANGA",'departamento_id'=> "27"],
            ['id'=>"913",'municipio'=> "CABRERA",'departamento_id'=> "27"],
            ['id'=>"914",'municipio'=> "CALIFORNIA",'departamento_id'=> "27"],
            ['id'=>"915",'municipio'=> "CAPITANEJO",'departamento_id'=> "27"],
            ['id'=>"916",'municipio'=> "CARCASI",'departamento_id'=> "27"],
            ['id'=>"917",'municipio'=> "CEPITA",'departamento_id'=> "27"],
            ['id'=>"918",'municipio'=> "CERRITO",'departamento_id'=> "27"],
            ['id'=>"919",'municipio'=> "CHARALÁ",'departamento_id'=> "27"],
            ['id'=>"920",'municipio'=> "CHARTA",'departamento_id'=> "27"],
            ['id'=>"921",'municipio'=> "CHIMA",'departamento_id'=> "27"],
            ['id'=>"922",'municipio'=> "CHIPATÁ",'departamento_id'=> "27"],
            ['id'=>"923",'municipio'=> "CIMITARRA",'departamento_id'=> "27"],
            ['id'=>"924",'municipio'=> "CONCEPCIÓN",'departamento_id'=> "27"],
            ['id'=>"925",'municipio'=> "CONFINES",'departamento_id'=> "27"],
            ['id'=>"926",'municipio'=> "CONTRATACIÓN",'departamento_id'=> "27"],
            ['id'=>"927",'municipio'=> "COROMORO",'departamento_id'=> "27"],
            ['id'=>"928",'municipio'=> "CURITÍ",'departamento_id'=> "27"],
            ['id'=>"929",'municipio'=> "EL CARMEN",'departamento_id'=> "27"],
            ['id'=>"930",'municipio'=> "EL GUACAMAYO",'departamento_id'=> "27"],
            ['id'=>"931",'municipio'=> "EL PEÑÓN",'departamento_id'=> "27"],
            ['id'=>"932",'municipio'=> "EL PLAYÓN",'departamento_id'=> "27"],
            ['id'=>"933",'municipio'=> "ENCINO",'departamento_id'=> "27"],
            ['id'=>"934",'municipio'=> "ENCISO",'departamento_id'=> "27"],
            ['id'=>"935",'municipio'=> "FLORIÁN",'departamento_id'=> "27"],
            ['id'=>"936",'municipio'=> "FLORIDABLANCA",'departamento_id'=> "27"],
            ['id'=>"937",'municipio'=> "GALÁN",'departamento_id'=> "27"],
            ['id'=>"938",'municipio'=> "GAMBITA",'departamento_id'=> "27"],
            ['id'=>"939",'municipio'=> "GIRÓN",'departamento_id'=> "27"],
            ['id'=>"940",'municipio'=> "GUACA",'departamento_id'=> "27"],
            ['id'=>"941",'municipio'=> "GUADALUPE",'departamento_id'=> "27"],
            ['id'=>"942",'municipio'=> "GUAPOTA",'departamento_id'=> "27"],
            ['id'=>"943",'municipio'=> "GUAVATÁ",'departamento_id'=> "27"],
            ['id'=>"944",'municipio'=> "GUEPSA",'departamento_id'=> "27"],
            ['id'=>"945",'municipio'=> "HATO",'departamento_id'=> "27"],
            ['id'=>"946",'municipio'=> "JESÚS MARIA",'departamento_id'=> "27"],
            ['id'=>"947",'municipio'=> "JORDÁN",'departamento_id'=> "27"],
            ['id'=>"948",'municipio'=> "LA BELLEZA",'departamento_id'=> "27"],
            ['id'=>"949",'municipio'=> "LA PAZ",'departamento_id'=> "27"],
            ['id'=>"950",'municipio'=> "LANDAZURI",'departamento_id'=> "27"],
            ['id'=>"951",'municipio'=> "LEBRIJA",'departamento_id'=> "27"],
            ['id'=>"952",'municipio'=> "LOS SANTOS",'departamento_id'=> "27"],
            ['id'=>"953",'municipio'=> "MACARAVITA",'departamento_id'=> "27"],
            ['id'=>"954",'municipio'=> "MÁLAGA",'departamento_id'=> "27"],
            ['id'=>"955",'municipio'=> "MATANZA",'departamento_id'=> "27"],
            ['id'=>"956",'municipio'=> "MOGOTES",'departamento_id'=> "27"],
            ['id'=>"957",'municipio'=> "MOLAGAVITA",'departamento_id'=> "27"],
            ['id'=>"958",'municipio'=> "OCAMONTE",'departamento_id'=> "27"],
            ['id'=>"959",'municipio'=> "OIBA",'departamento_id'=> "27"],
            ['id'=>"960",'municipio'=> "ONZAGA",'departamento_id'=> "27"],
            ['id'=>"961",'municipio'=> "PALMAR",'departamento_id'=> "27"],
            ['id'=>"962",'municipio'=> "PALMAS DEL SOCORRO",'departamento_id'=> "27"],
            ['id'=>"963",'municipio'=> "PÁRAMO",'departamento_id'=> "27"],
            ['id'=>"964",'municipio'=> "PIEDECUESTA",'departamento_id'=> "27"],
            ['id'=>"965",'municipio'=> "PINCHOTE",'departamento_id'=> "27"],
            ['id'=>"966",'municipio'=> "PUENTE NACIONAL",'departamento_id'=> "27"],
            ['id'=>"967",'municipio'=> "PUERTO PARRA",'departamento_id'=> "27"],
            ['id'=>"968",'municipio'=> "PUERTO WILCHES",'departamento_id'=> "27"],
            ['id'=>"969",'municipio'=> "RIONEGRO",'departamento_id'=> "27"],
            ['id'=>"970",'municipio'=> "SABANA DE TORRES",'departamento_id'=> "27"],
            ['id'=>"971",'municipio'=> "SAN ANDRÉS",'departamento_id'=> "27"],
            ['id'=>"972",'municipio'=> "SAN BENITO",'departamento_id'=> "27"],
            ['id'=>"973",'municipio'=> "SAN GIL",'departamento_id'=> "27"],
            ['id'=>"974",'municipio'=> "SAN JOAQUÍN",'departamento_id'=> "27"],
            ['id'=>"975",'municipio'=> "SAN JOSÉ DE MIRANDA",'departamento_id'=> "27"],
            ['id'=>"976",'municipio'=> "SAN MIGUEL",'departamento_id'=> "27"],
            ['id'=>"977",'municipio'=> "SAN VICENTE DE CHUCURÍ",'departamento_id'=> "27"],
            ['id'=>"978",'municipio'=> "SANTA BÁRBARA",'departamento_id'=> "27"],
            ['id'=>"979",'municipio'=> "SANTA HELENA",'departamento_id'=> "27"],
            ['id'=>"980",'municipio'=> "SIMACOTA",'departamento_id'=> "27"],
            ['id'=>"981",'municipio'=> "SOCORRO",'departamento_id'=> "27"],
            ['id'=>"982",'municipio'=> "SUAITA",'departamento_id'=> "27"],
            ['id'=>"983",'municipio'=> "SUCRE",'departamento_id'=> "27"],
            ['id'=>"984",'municipio'=> "SURATA",'departamento_id'=> "27"],
            ['id'=>"985",'municipio'=> "TONA",'departamento_id'=> "27"],
            ['id'=>"986",'municipio'=> "VALLE SAN JOSÉ",'departamento_id'=> "27"],
            ['id'=>"987",'municipio'=> "VÉLEZ",'departamento_id'=> "27"],
            ['id'=>"988",'municipio'=> "VETAS",'departamento_id'=> "27"],
            ['id'=>"989",'municipio'=> "VILLANUEVA",'departamento_id'=> "27"],
            ['id'=>"990",'municipio'=> "ZAPATOCA",'departamento_id'=> "27"],
            ['id'=>"991",'municipio'=> "BUENAVISTA",'departamento_id'=> "28"],
            ['id'=>"992",'municipio'=> "CAIMITO",'departamento_id'=> "28"],
            ['id'=>"993",'municipio'=> "CHALÁN",'departamento_id'=> "28"],
            ['id'=>"994",'municipio'=> "COLOSO",'departamento_id'=> "28"],
            ['id'=>"995",'municipio'=> "COROZAL",'departamento_id'=> "28"],
            ['id'=>"996",'municipio'=> "EL ROBLE",'departamento_id'=> "28"],
            ['id'=>"997",'municipio'=> "GALERAS",'departamento_id'=> "28"],
            ['id'=>"998",'municipio'=> "GUARANDA",'departamento_id'=> "28"],
            ['id'=>"999",'municipio'=> "LA UNIÓN",'departamento_id'=> "28"],
            ['id'=>"1000",'municipio'=> "LOS PALMITOS",'departamento_id'=> "28"],
            ['id'=>"1001",'municipio'=> "MAJAGUAL",'departamento_id'=> "28"],
            ['id'=>"1002",'municipio'=> "MORROA",'departamento_id'=> "28"],
            ['id'=>"1003",'municipio'=> "OVEJAS",'departamento_id'=> "28"],
            ['id'=>"1004",'municipio'=> "PALMITO",'departamento_id'=> "28"],
            ['id'=>"1005",'municipio'=> "SAMPUES",'departamento_id'=> "28"],
            ['id'=>"1006",'municipio'=> "SAN BENITO ABAD",'departamento_id'=> "28"],
            ['id'=>"1007",'municipio'=> "SAN JUAN DE BETULIA",'departamento_id'=> "28"],
            ['id'=>"1008",'municipio'=> "SAN MARCOS",'departamento_id'=> "28"],
            ['id'=>"1009",'municipio'=> "SAN ONOFRE",'departamento_id'=> "28"],
            ['id'=>"1010",'municipio'=> "SAN PEDRO",'departamento_id'=> "28"],
            ['id'=>"1011",'municipio'=> "SINCÉ",'departamento_id'=> "28"],
            ['id'=>"1012",'municipio'=> "SINCELEJO",'departamento_id'=> "28"],
            ['id'=>"1013",'municipio'=> "SUCRE",'departamento_id'=> "28"],
            ['id'=>"1014",'municipio'=> "TOLÚ",'departamento_id'=> "28"],
            ['id'=>"1015",'municipio'=> "TOLUVIEJO",'departamento_id'=> "28"],
            ['id'=>"1016",'municipio'=> "ALPUJARRA",'departamento_id'=> "29"],
            ['id'=>"1017",'municipio'=> "ALVARADO",'departamento_id'=> "29"],
            ['id'=>"1018",'municipio'=> "AMBALEMA",'departamento_id'=> "29"],
            ['id'=>"1019",'municipio'=> "ANZOATEGUI",'departamento_id'=> "29"],
            ['id'=>"1020",'municipio'=> "ARMERO (GUAYABAL)",'departamento_id'=> "29"],
            ['id'=>"1021",'municipio'=> "ATACO",'departamento_id'=> "29"],
            ['id'=>"1022",'municipio'=> "CAJAMARCA",'departamento_id'=> "29"],
            ['id'=>"1023",'municipio'=> "CARMEN DE APICALÁ",'departamento_id'=> "29"],
            ['id'=>"1024",'municipio'=> "CASABIANCA",'departamento_id'=> "29"],
            ['id'=>"1025",'municipio'=> "CHAPARRAL",'departamento_id'=> "29"],
            ['id'=>"1026",'municipio'=> "COELLO",'departamento_id'=> "29"],
            ['id'=>"1027",'municipio'=> "COYAIMA",'departamento_id'=> "29"],
            ['id'=>"1028",'municipio'=> "CUNDAY",'departamento_id'=> "29"],
            ['id'=>"1029",'municipio'=> "DOLORES",'departamento_id'=> "29"],
            ['id'=>"1030",'municipio'=> "ESPINAL",'departamento_id'=> "29"],
            ['id'=>"1031",'municipio'=> "FALÁN",'departamento_id'=> "29"],
            ['id'=>"1032",'municipio'=> "FLANDES",'departamento_id'=> "29"],
            ['id'=>"1033",'municipio'=> "FRESNO",'departamento_id'=> "29"],
            ['id'=>"1034",'municipio'=> "GUAMO",'departamento_id'=> "29"],
            ['id'=>"1035",'municipio'=> "HERVEO",'departamento_id'=> "29"],
            ['id'=>"1036",'municipio'=> "HONDA",'departamento_id'=> "29"],
            ['id'=>"1037",'municipio'=> "IBAGUÉ",'departamento_id'=> "29"],
            ['id'=>"1038",'municipio'=> "ICONONZO",'departamento_id'=> "29"],
            ['id'=>"1039",'municipio'=> "LÉRIDA",'departamento_id'=> "29"],
            ['id'=>"1040",'municipio'=> "LÍBANO",'departamento_id'=> "29"],
            ['id'=>"1041",'municipio'=> "MARIQUITA",'departamento_id'=> "29"],
            ['id'=>"1042",'municipio'=> "MELGAR",'departamento_id'=> "29"],
            ['id'=>"1043",'municipio'=> "MURILLO",'departamento_id'=> "29"],
            ['id'=>"1044",'municipio'=> "NATAGAIMA",'departamento_id'=> "29"],
            ['id'=>"1045",'municipio'=> "ORTEGA",'departamento_id'=> "29"],
            ['id'=>"1046",'municipio'=> "PALOCABILDO",'departamento_id'=> "29"],
            ['id'=>"1047",'municipio'=> "PIEDRAS PLANADAS",'departamento_id'=> "29"],
            ['id'=>"1048",'municipio'=> "PRADO",'departamento_id'=> "29"],
            ['id'=>"1049",'municipio'=> "PURIFICACIÓN",'departamento_id'=> "29"],
            ['id'=>"1050",'municipio'=> "RIOBLANCO",'departamento_id'=> "29"],
            ['id'=>"1051",'municipio'=> "RONCESVALLES",'departamento_id'=> "29"],
            ['id'=>"1052",'municipio'=> "ROVIRA",'departamento_id'=> "29"],
            ['id'=>"1053",'municipio'=> "SALDAÑA",'departamento_id'=> "29"],
            ['id'=>"1054",'municipio'=> "SAN ANTONIO",'departamento_id'=> "29"],
            ['id'=>"1055",'municipio'=> "SAN LUIS",'departamento_id'=> "29"],
            ['id'=>"1056",'municipio'=> "SANTA ISABEL",'departamento_id'=> "29"],
            ['id'=>"1057",'municipio'=> "SUÁREZ",'departamento_id'=> "29"],
            ['id'=>"1058",'municipio'=> "VALLE DE SAN JUAN",'departamento_id'=> "29"],
            ['id'=>"1059",'municipio'=> "VENADILLO",'departamento_id'=> "29"],
            ['id'=>"1060",'municipio'=> "VILLAHERMOSA",'departamento_id'=> "29"],
            ['id'=>"1061",'municipio'=> "VILLARRICA",'departamento_id'=> "29"],
            ['id'=>"1062",'municipio'=> "ALCALÁ",'departamento_id'=> "30"],
            ['id'=>"1063",'municipio'=> "ANDALUCÍA",'departamento_id'=> "30"],
            ['id'=>"1064",'municipio'=> "ANSERMA NUEVO",'departamento_id'=> "30"],
            ['id'=>"1065",'municipio'=> "ARGELIA",'departamento_id'=> "30"],
            ['id'=>"1066",'municipio'=> "BOLÍVAR",'departamento_id'=> "30"],
            ['id'=>"1067",'municipio'=> "BUENAVENTURA",'departamento_id'=> "30"],
            ['id'=>"1068",'municipio'=> "BUGA",'departamento_id'=> "30"],
            ['id'=>"1069",'municipio'=> "BUGALAGRANDE",'departamento_id'=> "30"],
            ['id'=>"1070",'municipio'=> "CAICEDONIA",'departamento_id'=> "30"],
            ['id'=>"1071",'municipio'=> "CALI",'departamento_id'=> "30"],
            ['id'=>"1072",'municipio'=> "CALIMA (DARIEN)",'departamento_id'=> "30"],
            ['id'=>"1073",'municipio'=> "CANDELARIA",'departamento_id'=> "30"],
            ['id'=>"1074",'municipio'=> "CARTAGO",'departamento_id'=> "30"],
            ['id'=>"1075",'municipio'=> "DAGUA",'departamento_id'=> "30"],
            ['id'=>"1076",'municipio'=> "EL AGUILA",'departamento_id'=> "30"],
            ['id'=>"1077",'municipio'=> "EL CAIRO",'departamento_id'=> "30"],
            ['id'=>"1078",'municipio'=> "EL CERRITO",'departamento_id'=> "30"],
            ['id'=>"1079",'municipio'=> "EL DOVIO",'departamento_id'=> "30"],
            ['id'=>"1080",'municipio'=> "FLORIDA",'departamento_id'=> "30"],
            ['id'=>"1081",'municipio'=> "GINEBRA GUACARI",'departamento_id'=> "30"],
            ['id'=>"1082",'municipio'=> "JAMUNDÍ",'departamento_id'=> "30"],
            ['id'=>"1083",'municipio'=> "LA CUMBRE",'departamento_id'=> "30"],
            ['id'=>"1084",'municipio'=> "LA UNIÓN",'departamento_id'=> "30"],
            ['id'=>"1085",'municipio'=> "LA VICTORIA",'departamento_id'=> "30"],
            ['id'=>"1086",'municipio'=> "OBANDO",'departamento_id'=> "30"],
            ['id'=>"1087",'municipio'=> "PALMIRA",'departamento_id'=> "30"],
            ['id'=>"1088",'municipio'=> "PRADERA",'departamento_id'=> "30"],
            ['id'=>"1089",'municipio'=> "RESTREPO",'departamento_id'=> "30"],
            ['id'=>"1090",'municipio'=> "RIO FRÍO",'departamento_id'=> "30"],
            ['id'=>"1091",'municipio'=> "ROLDANILLO",'departamento_id'=> "30"],
            ['id'=>"1092",'municipio'=> "SAN PEDRO",'departamento_id'=> "30"],
            ['id'=>"1093",'municipio'=> "SEVILLA",'departamento_id'=> "30"],
            ['id'=>"1094",'municipio'=> "TORO",'departamento_id'=> "30"],
            ['id'=>"1095",'municipio'=> "TRUJILLO",'departamento_id'=> "30"],
            ['id'=>"1096",'municipio'=> "TULÚA",'departamento_id'=> "30"],
            ['id'=>"1097",'municipio'=> "ULLOA",'departamento_id'=> "30"],
            ['id'=>"1098",'municipio'=> "VERSALLES",'departamento_id'=> "30"],
            ['id'=>"1099",'municipio'=> "VIJES",'departamento_id'=> "30"],
            ['id'=>"1100",'municipio'=> "YOTOCO",'departamento_id'=> "30"],
            ['id'=>"1101",'municipio'=> "YUMBO",'departamento_id'=> "30"],
            ['id'=>"1102",'municipio'=> "ZARZAL",'departamento_id'=> "30"],
            ['id'=>"1103",'municipio'=> "CARURÚ",'departamento_id'=> "31"],
            ['id'=>"1104",'municipio'=> "MITÚ",'departamento_id'=> "31"],
            ['id'=>"1105",'municipio'=> "PACOA",'departamento_id'=> "31"],
            ['id'=>"1106",'municipio'=> "PAPUNAUA",'departamento_id'=> "31"],
            ['id'=>"1107",'municipio'=> "TARAIRA",'departamento_id'=> "31"],
            ['id'=>"1108",'municipio'=> "YAVARATÉ",'departamento_id'=> "31"],
            ['id'=>"1109",'municipio'=> "CUMARIBO",'departamento_id'=> "32"],
            ['id'=>"1110",'municipio'=> "LA PRIMAVERA",'departamento_id'=> "32"],
            ['id'=>"1111",'municipio'=> "PUERTO CARREÑO",'departamento_id'=> "32"],
            ['id'=>"1112",'municipio'=> "SANTA ROSALIA",'departamento_id'=> "32"]
        ]);
    }
}
